name: need_doctors
description: A new Flutter project.

version: 1.0.0+1 

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  awesome_dialog: ^1.3.2
  cached_network_image: ^2.5.0
  carousel_pro: ^1.0.0
  carousel_slider: ^3.0.0
  configurable_expansion_tile: ^1.0.0

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  date_time_picker: ^1.1.1
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0
  sms: ^0.2.4
  flutter_local_notifications: ^4.0.1+2
  flutter_secure_storage: ^4.2.0
  flutter_svg: ^0.22.0
  flutter_swiper: ^1.1.6
  fluttertoast: ^8.0.7
  google_fonts: ^1.0.0
  http: ^0.12.2
  http_parser: ^3.1.4
  image: ^3.0.2
  #  image_cropper: ^1.3.1
  image_cropper: ^1.4.0
  image_picker: ^0.6.7+22
  infinite_scroll_pagination: ^3.0.1+1
  lottie: ^1.0.1
  multi_select_flutter: ^4.0.0
  objectbox: ^1.1.1
  objectbox_flutter_libs: any
  path_provider: ^1.3.0
  # hive: ^2.0.4
  # hive_flutter: ^1.1.0
  permission_handler: ^5.1.0+2
  photo_view: ^0.10.2
  simple_animations: ^2.5.1
  sizer: ^2.0.13
  #  sqflite: ^2.0.0+3
  tesseract_ocr: any
  url_launcher: ^6.0.2
  your_splash: ^0.2.2
  logger: ^1.1.0

dependency_overrides:
  build_runner: ^1.0.0
  path_provider: ^2.0.2
  http_parser: ^4.0.0

dev_dependencies:
  build_runner: ^2.0.6
  flat_buffers: ^1.12.0
  flutter_phone_direct_caller: any
  flutter_test:
    sdk: flutter
  get: ^3.24.0
  objectbox_generator: any
  page_transition: ^2.0.2
  mobile_number: ^1.0.3

flutter_icons:
  android: true
  image_path: "asset/images/doctor.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/
    - asset/lottie/
    - asset/logo.png
    - asset/svg/treatment_set.svg
    - asset/doctor_boy.svg
    - asset/logog.png
    - asset/password.png
    - asset/Avatar1.png
    - asset/logo5.PNG
    - asset/1.PNG
    - asset/2.PNG
    - asset/3.PNG
    - asset/star.png
    - asset/Dashbord.png
    - asset/Vector.png
    - asset/Vector2.png
    - asset/vector3.PNG
    - asset/svg/
    - asset/svg/types/
    - asset/images/
    - assets/
    - assets/tessdata/
    - asset/home/
    - asset/drugs/
  fonts:
    - family: Sofia Pro
      fonts:
        - asset: fonts/sofiapro-light.otf
          weight: 300
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-ExtraBold.otf
          weight: 800
        - asset: fonts/Gilroy-Light.otf
          weight: 300
