name: need_doctors
description: A new Flutter project.

#Changinmg
#Changoing file again inshohan branch
#Changing from alpha Habib
#Changing from shohan
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  awesome_dialog: null
  cached_network_image: ^2.5.0
  configurable_expansion_tile: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  flutter_launcher_icons: ^0.9.0
  flutter_secure_storage: ^4.2.0
  flutter_svg: ^0.22.0
  flutter_swiper: ^1.1.6
  fluttertoast: ^8.0.7
  google_fonts: ^1.0.0
  http: ^0.12.2
  http_parser: ^3.1.4
  image: ^3.0.2
  #  image_cropper: ^1.3.1
  image_cropper: ^1.4.0
  image_picker: ^0.6.7+22
  infinite_scroll_pagination: ^3.0.1+1
  multi_select_flutter: ^4.0.0
  path_provider: ^1.6.7
  simple_animations: ^1.3.3
  sizer: ^2.0.13
  sqflite: ^2.0.0+3
  tesseract_ocr: ^0.3.1
  url_launcher: ^6.0.2
  your_splash: ^0.2.2
  lottie: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "asset/images/doctor.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - asset/lottie/
    - asset/logo.png
    - asset/svg/treatment_set.svg
    - asset/doctor_boy.svg
    - asset/logog.png
    - asset/password.png
    - asset/Avatar1.png
    - asset/logo5.PNG
    - asset/1.PNG
    - asset/2.PNG
    - asset/3.PNG
    - asset/11.db
    - asset/star.png
    - asset/Dashbord.png
    - asset/Vector.png
    - asset/Vector2.png
    - asset/vector3.PNG
    - asset/svg/
    - asset/svg/types/
    - asset/images/
    - assets/
    - assets/tessdata/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
