final List occuptoinlist = [
  "Doctor",
  "Intern Doctor",
  "MATS Student",
  "Medical Student",
  "Nurse",
  "Nursing Student",
  "Pharmaceutical Professional",
  "SACMO",
  "Others"
];

final List thanatlist = [
  "Bagerhat",
  "Bandarban",
  "Barguna",
  "Barisal",
  "Bhola",
  "Bogra",
  "Brahmanbaria",
  "Chandpur",
  "Chuadanga",
  "Comilla",
  "Cox's Bazar",
  "Dhaka",
  "Faridpur",
  "Feni",
  "Gaibandha",
  "Gazipur",
  "Gopalganj",
  "Habiganj"
      "Jaipurhat"
      "Jamalpur",
  "Jessore",
  "Jhalakati",
  "Jhenaidah",
  "Khagrachari",
  "Khulna",
  "Kishoreganj",
  "Kurigram",
  "Kushtia",
  "Lakshmipur",
  "Lalmonirhat",
  "Madaripur",
  "Magura",
  "Manikganj",
  "Meherpur",
  "Moulvibazar",
  "Munshiganj",
  "Mymensingh",
  "Naogaon",
  "Narail",
  "Narayanganj",
  "Narsingdi",
  "Natore",
  "Nawabganj",
  "Netrakona",
  "Nilphamari",
  "Noakhali",
  "Pabna",
  "Panchagarh",
  "Parbattya Chattagram",
  "Patuakhali",
  "Pirojpur",
  "Rajbari",
  "Rajshahi",
  "Rangpur",
  "Satkhira",
  "Shariatpur",
  "Sherpur",
  "Sirajganj",
  "Sunamganj",
  "Sylhet",
  "Tangail",
  "Thakurgaon",
];

final List districtlist = [
  "Bagerhat",
  "Bandarban",
  "Barguna",
  "Barisal",
  "Bhola",
  "Bogra",
  "Brahmanbaria",
  "Chandpur",
  "Chuadanga"
      "Comilla",
  "Cox's Bazar",
  "Dhaka",
  "Faridpur",
  "Feni",
  "Gaibandha",
  "Gazipur",
  "Gopalganj",
  "Habiganj"
      "Jaipurhat"
      "Jamalpur",
  "Jessore",
  "Jhalakati",
  "Jhenaidah",
  "Khagrachari",
  "Khulna",
  "Kishoreganj",
  "Kurigram",
  "Kushtia",
  "Lakshmipur",
  "Lalmonirhat",
  "Madaripur",
  "Magura",
  "Manikganj",
  "Meherpur",
  "Moulvibazar",
  "Munshiganj",
  "Mymensingh",
  "Naogaon",
  "Narail",
  "Narayanganj",
  "Narsingdi",
  "Natore",
  "Nawabganj",
  "Netrakona",
  "Nilphamari",
  "Noakhali",
  "Pabna",
  "Panchagarh",
  "Parbattya Chattagram",
  "Patuakhali",
  "Pirojpur",
  "Rajbari",
  "Rajshahi",
  "Rangpur",
  "Satkhira",
  "Shariatpur",
  "Sherpur",
  "Sirajganj",
  "Sunamganj",
  "Sylhet",
  "Tangail",
  "Thakurgaon",
];

final List specializationList = [
  "Anesthesia & ICU/এনেস্থিসিয়া এবং আই,সি,ইউ",
  "Cancer Surgeons/ক্যানসার সার্জন",
  "Cardio-Vascular Surgeons/কার্ডিও ভাস্কুলার সার্জন",
  "Cardiologists/কার্ডিওলজিস্ট",
  "Colorectal Surgeons/কোলোরেকটাল সার্জন",
  "Critical Care Medicine/ক্রিটিকল কেয়ার মেডিসিন",
  "Dentists/ডেন্টিস",
  "Dermatologists/ডারমাটোলজিস্ট",
  "Diabetologists/ডাইবেটোলজিস্ট",
  "ENT Specialists/ই, এন, টি স্পেশালিষ্ট ",
  "Endocrinologists/এনডোক্রাইনোলজিস্ট",
  "Gastroenteritis's/গ্যাসস্ট্রোইনটেরোলজিস্ট",
  "General & Laparoscopic/সাধারণ ল্যাপ্যারস্কোপিক",
  "General Physicians(G.p.)/সাধারণ চিকিৎসক ",
  "Gynecologist & Obs /গাইনিকোলজিস্ট & অবস্",
  "Hemaologists/হিমোটোলজিস্ট",
  "Hepatobiliary Surgeons/হেপ্যাটোবিলিয়ার সার্জন",
  "Hepatologists/হেপ্যাটোলজিস্ট",
  "Infertility Specialists/ইনফারটিলিটি স্পেশালিষ্ট ",
  " Medicine Specilists/মেডিসিন স্পেশালিষ্ট ",
  "Nephrologist/নেফরোলজিস্ট",
  "Neurologists/নিউরোলজিস্ট",
  "Oncologists/ওনকলজিস্ট",
  "Ophthalmologists/অফ্থ্যালমোল্যাজিস্ট(চক্ষুরোগ)",
  "Orofacial & Maxillary/অরফিসিয়াল এবং ম্যাকজিলারি",
  "Orthopaedic Surgeons/অর্থপেডিক সর্জন",
  "Pediatric Surgeons/পিডিয়াট্রিক্স সার্জন",
  "Pediatricians/পেডিয়াট্রিসিয়ান",
  "Physical Medicine/ফিজিক্যাল মেডিসিন",
  "Plastic Surgeons/প্লাস্টিক সার্জন",
  "Psychiatrists/সাইক্রেটিস্ট",
  "Respiratory Medicine/রেস্পাইরেট্যারি মেডিসি",
  "Rheumatology/রিউম্যাটল্যাজি ",
  "Skin Specialists/স্কিন স্পেশালিস্ট",
  "Urologist/ইউরোলজিস্ট",
  "Others/অন্নান্য",
];

final List districtListFull = [
   {"district_id": 72, "name": "AC Roy road/এ সি  রায় রোড "},
  {"district_id": 72, "name": "Abdul Hadi Lane/আব্দুল হাদি লেন "},
  {"district_id": 72, "name": "Abdul bani road/আব্দুল বাণী রোড "},
  {"district_id": 72, "name": "Abed Dali Road/আবেদ ডালি রোড "},
  {"district_id": 20, "name": "Abhaynagar/অভয়নগর "},
  {"district_id": 72, "name": "Abhidas Lane/অভিদাস লেন "},
  {"district_id": 72, "name": "Abul Hasnat Road/আবুল হাসনাত রোড "},
  {"district_id": 71, "name": "Abul Hotel Bus Stop/আবুল হোটেল বাস স্টপ "},
  {"district_id": 72, "name": "Abul hasnat lane/আবুল হাসনাত লেন "},
  {"district_id": 72, "name": "Abul khairat Road/আবুল খয়রাত রোড "},
  {"district_id": 72, "name": "Abul khairat Road/আবুল খয়রাত রোড "},
  {"district_id": 71, "name": "Adabor/আদাবর "},
  {"district_id": 14, "name": "Adamdighi/আদমদীঘি "},
  {"district_id": 71, "name": "Adarsha Bag/আদর্শ ব্যাগ "},
  {"district_id": 55, "name": "Aditmari/আদিতমারী "},
  {"district_id": 71, "name": "Aftab nagar/আফতাব নাগার "},
  {"district_id": 72, "name": "Aga sadek road/এগ সাদেক রোড "},
  {"district_id": 33, "name": "Agailjhara/আগাইলঝাড়া "},
  {"district_id": 72, "name": "Agamasi Lane/আগামাসি লেন "},
  {"district_id": 71, "name": "Agargaon/আগারগাঁও"},
  {"district_id": 71, "name": "Ahmed Nagar/আহমেদ নগর "},
  {"district_id": 72, "name": "Ahmedbagh/আহমেদবাগ "},
  {"district_id": 72, "name": "Ahsan Ullah Road/ আহসান উল্লা রোড "},
  {"district_id": 38, "name": "Ajmiriganj/আজমিরীগঞ্জ "},
 {"district_id": 71, "name": "Ajompur/আজমপুর "},
  {"district_id": 3, "name": "Akhaura/আখাউড়া "},
  {"district_id": 17, "name": "Akkelpur/আক্কেলপুর "},
  {"district_id": 72, "name": "Akshay Das Lane/অক্ষয় দাস লেন "},
  {"district_id": 72, "name": "Al Amin Road/আল আমিন রোড "},
  {"district_id": 24, "name": "Alamdanga/আলমগংগা "},
  {"district_id": 72, "name": "Alamganj Road/আলামগঞ্জ রোড "},
  {"district_id": 52, "name": "Alfadanga/আলফাডাঙ্গা "},
  {"district_id": 72, "name": "Ali hossain Khan lane/আলী হোসাইন খান লেন "},
  {"district_id": 11, "name": "Alikadam/আলীকদম "},
  {"district_id": 72, "name": "Aminabad colony moghbaraz/আমিনাবাদ কলোনী মোঘলবাজার "},
  {"district_id": 72, "name": "Aminbagh/আমিনবাগ "},
  {"district_id": 35, "name": "Amtali/আমতলী "},
  {"district_id": 71, "name": "Ananda Nagar/আনন্দ নগর "},
  {"district_id": 72, "name": "Anond mohan boshak Lane/আনন্দ মহান বসাক লেন"},
  {"district_id": 8, "name": "Anwara/আনোয়ারা"},
  {"district_id": 71, "name": "Apollo Hospital/অ্যাপোলো হাসপাতাল "},
  {"district_id": 43, "name": "Araihazar/আড়াইহাজার "},
  {"district_id": 72, "name": "Arambagh/আরামবাগ "},

  // {"id": 28, "division_id": 3, "name": "Bagerhat"},
  // {"id": 11, "division_id": 1, "name": "Bandarban"},
  // {"id": 35, "division_id": 4, "name": "Barguna"},
  // {"id": 33, "division_id": 4, "name": "Barisal"},
  // {"id": 34, "division_id": 4, "name": "Bhola"},
  // {"id": 14, "division_id": 2, "name": "Bogura"},
  // {"id": 3, "division_id": 1, "name": "Brahmanbaria"},
  // {"id": 6, "division_id": 1, "name": "Chandpur"},
  // {"id": 18, "division_id": 2, "name": "Chapainawabganj"},
  // {"id": 8, "division_id": 1, "name": "Chattogram"},
  // {"id": 24, "division_id": 3, "name": "Chuadanga"},
  // {"id": 1, "division_id": 1, "name": "Comilla"},
  // {"id": 9, "division_id": 1, "name": "Coxsbazar"},
  // {"id": 47, "division_id": 6, "name": "Dhaka"},
  // {"id": 71, "division_id": 6, "name": "Dhaka-North"},
  // {"id": 72, "division_id": 6, "name": "Dhaka-South"},
  // {"id": 54, "division_id": 7, "name": "Dinajpur"},
  // {"id": 52, "division_id": 6, "name": "Faridpur"},
  // {"id": 2, "division_id": 1, "name": "Feni"},
  // {"id": 57, "division_id": 7, "name": "Gaibandha"},
  // {"id": 41, "division_id": 6, "name": "Gazipur"},
  // {"id": 51, "division_id": 6, "name": "Gopalganj"},
  // {"id": 38, "division_id": 5, "name": "Habiganj"},
  // {"id": 63, "division_id": 8, "name": "Jamalpur"},
  // {"id": 20, "division_id": 3, "name": "Jashore"},
  // {"id": 30, "division_id": 4, "name": "Jhalakathi"},
  // {"id": 29, "division_id": 3, "name": "Jhenaidah"},
  // {"id": 17, "division_id": 2, "name": "Joypurhat"},
  // {"id": 10, "division_id": 1, "name": "Khagrachhari"},
  // {"id": 27, "division_id": 3, "name": "Khulna"},
  // {"id": 45, "division_id": 6, "name": "Kishoreganj"},
  // {"id": 60, "division_id": 7, "name": "Kurigram"},
  // {"id": 25, "division_id": 3, "name": "Kushtia"},
  // {"id": 7, "division_id": 1, "name": "Lakshmipur"},
  // {"id": 55, "division_id": 7, "name": "Lalmonirhat"},
  // {"id": 50, "division_id": 6, "name": "Madaripur"},
  // {"id": 26, "division_id": 3, "name": "Magura"},
  // {"id": 46, "division_id": 6, "name": "Manikganj"},
  // {"id": 22, "division_id": 3, "name": "Meherpur"},
  // {"id": 37, "division_id": 5, "name": "Moulvibazar"},
  // {"id": 48, "division_id": 6, "name": "Munshiganj"},
  // {"id": 62, "division_id": 8, "name": "Mymensingh"},
  // {"id": 19, "division_id": 2, "name": "Naogaon"},
  // {"id": 23, "division_id": 3, "name": "Narail"},
  // {"id": 43, "division_id": 6, "name": "Narayanganj"},
  // {"id": 40, "division_id": 6, "name": "Narsingdi"},
  // {"id": 16, "division_id": 2, "name": "Natore"},
  // {"id": 64, "division_id": 8, "name": "Netrokona"},
  // {"id": 56, "division_id": 7, "name": "Nilphamari"},
  // {"id": 5, "division_id": 1, "name": "Noakhali"},
  // {"id": 13, "division_id": 2, "name": "Pabna"},
  // {"id": 53, "division_id": 7, "name": "Panchagarh"},
  // {"id": 31, "division_id": 4, "name": "Patuakhali"},
  // {"id": 32, "division_id": 4, "name": "Pirojpur"},
  // {"id": 49, "division_id": 6, "name": "Rajbari"},
  // {"id": 15, "division_id": 2, "name": "Rajshahi"},
  // {"id": 4, "division_id": 1, "name": "Rangamati"},
  // {"id": 59, "division_id": 7, "name": "Rangpur"},
  // {"id": 21, "division_id": 3, "name": "Satkhira"},
  // {"id": 42, "division_id": 6, "name": "Shariatpur"},
  // {"id": 61, "division_id": 8, "name": "Sherpur"},
  // {"id": 12, "division_id": 2, "name": "Sirajganj"},
  // {"id": 39, "division_id": 5, "name": "Sunamganj"},
  // {"id": 36, "division_id": 5, "name": "Sylhet"},
  // {"id": 44, "division_id": 6, "name": "Tangail"},
  // {"id": 58, "division_id": 7, "name": "Thakurgaon"}
];
