final List districtListJson = [
  {"id": 28, "division_id": 3, "name": "Bagerhat - বাগেরহাট"},
  {"id": 11, "division_id": 1, "name": "Bandarban - বান্দরবান"},
  {"id": 35, "division_id": 4, "name": "Barguna - বরগুনা"},
  {"id": 33, "division_id": 4, "name": "Barisal - বরিশাল"},
  {"id": 34, "division_id": 4, "name": "Bhola - ভোলা"},
  {"id": 14, "division_id": 2, "name": "Bogura - বগুড়া "},
  {"id": 3, "division_id": 1, "name": "Brahmanbaria - ব্রাক্ষণবাড়িয়া"},
  {"id": 6, "division_id": 1, "name": "Chandpur - চাঁদপুর"},
  {"id": 18, "division_id": 2, "name": "Chapainawabganj - চাঁপাইনবাবগঞ্জ"},
  {"id": 8, "division_id": 1, "name": "Chattogram - চট্টগ্রাম "},
  {"id": 24, "division_id": 3, "name": "Chuadanga - চুয়াডাঙ্গা "},
  {"id": 1, "division_id": 1, "name": "Comilla - কুমিল্লা "},
  {"id": 9, "division_id": 1, "name": "Coxsbazar - কক্সবাজার"},
  {"id": 47, "division_id": 6, "name": "Dhaka District -  ঢাকা জেলা"},
  {"id": 80, "division_id": 6, "name": "Dhaka-North - ঢাকা উত্তর"},
  {"id": 81, "division_id": 6, "name": "Dhaka-South - ঢাকা দক্ষিন"},
  {"id": 54, "division_id": 7, "name": "Dinajpur - দিনাজপুর "},
  {"id": 52, "division_id": 6, "name": "Faridpur - ফরিদপুর "},
  {"id": 2, "division_id": 1, "name": "Feni - ফেনী"},
  {"id": 57, "division_id": 7, "name": "Gaibandha - গাইবান্ধা"},
  {"id": 41, "division_id": 6, "name": "Gazipur - গাজীপুর "},
  {"id": 51, "division_id": 6, "name": "Gopalganj - গোপালগঞ্জ "},
  {"id": 38, "division_id": 5, "name": "Habiganj - হবিগঞ্জ"},
  {"id": 63, "division_id": 8, "name": "Jamalpur - জামালপুর "},
  {"id": 20, "division_id": 3, "name": "Jashore - যশোর"},
  {"id": 30, "division_id": 4, "name": "Jhalakathi - ঝালুকাঠি "},
  {"id": 29, "division_id": 3, "name": "Jhenaidah - ঝিনাইদহ্"},
  {"id": 17, "division_id": 2, "name": "Joypurhat - জয়পুরহাট "},
  {"id": 10, "division_id": 1, "name": "Khagrachhari - খাগড়াছড়ি "},
  {"id": 27, "division_id": 3, "name": "Khulna - খুলনা "},
  {"id": 45, "division_id": 6, "name": "Kishoreganj - কিশোরগঞ্জ"},
  {"id": 60, "division_id": 7, "name": "Kurigram - কুড়িগ্রাম"},
  {"id": 25, "division_id": 3, "name": "Kushtia - কুষ্টিয়া "},
  {"id": 7, "division_id": 1, "name": "Lakshmipur - লক্ষীপুর"},
  {"id": 55, "division_id": 7, "name": "Lalmonirhat - লালমনিরহাট"},
  {"id": 50, "division_id": 6, "name": "Madaripur - মাদারীপুর "},
  {"id": 26, "division_id": 3, "name": "Magura - মাগুরা "},
  {"id": 46, "division_id": 6, "name": "Manikganj - মানিকগঞ্জ "},
  {"id": 22, "division_id": 3, "name": "Meherpur - মেহেরপুর "},
  {"id": 37, "division_id": 5, "name": "Moulvibazar - মৌলভীবাজার"},
  {"id": 48, "division_id": 6, "name": "Munshiganj - মুন্সিগঞ্জ"},
  {"id": 62, "division_id": 8, "name": "Mymensingh - ময়মনসিংহ"},
  {"id": 19, "division_id": 2, "name": "Naogaon - নওগাঁ"},
  {"id": 23, "division_id": 3, "name": "Narail - নড়াইল"},
  {"id": 43, "division_id": 6, "name": "Narayanganj - নারায়ণগঞ্জ"},
  {"id": 40, "division_id": 6, "name": "Narsingdi - নরসিংদী "},
  {"id": 16, "division_id": 2, "name": "Natore - নাটোর"},
  {"id": 64, "division_id": 8, "name": "Netrokona - নেত্রকোনা "},
  {"id": 56, "division_id": 7, "name": "Nilphamari - নীলফামারী"},
  {"id": 5, "division_id": 1, "name": "Noakhali - নোয়াখালী "},
  {"id": 13, "division_id": 2, "name": "Pabna - পাবনা"},
  {"id": 53, "division_id": 7, "name": "Panchagarh - পঞ্চগড়"},
  {"id": 31, "division_id": 4, "name": "Patuakhali - পটুয়াখালী"},
  {"id": 32, "division_id": 4, "name": "Pirojpur - পিরোজপুর"},
  {"id": 49, "division_id": 6, "name": "Rajabari - রাজবাড়ী"},
  {"id": 15, "division_id": 2, "name": "Rajshahi - রাজশাহী"},
  {"id": 4, "division_id": 1, "name": "Rangamati - রাঙ্গামাটি"},
  {"id": 59, "division_id": 7, "name": "Rangpur - রংপুর"},
  {"id": 21, "division_id": 3, "name": "Satkhira - সাতক্ষীরা"},
  {"id": 42, "division_id": 6, "name": "Shariatpur - শরিয়তপুর"},
  {"id": 61, "division_id": 8, "name": "Sherpur - শেরপুর"},
  {"id": 12, "division_id": 2, "name": "Sirajganj - সিরাজগঞ্জ"},
  {"id": 39, "division_id": 5, "name": "Sunamganj - সুনামগঞ্জ"},
  {"id": 36, "division_id": 5, "name": "Sylhet - সিলেট"},
  {"id": 44, "division_id": 6, "name": "Tangail - টাঙ্গাইল"},
  {"id": 58, "division_id": 7, "name": "Thakurgaon - ঠাকুরগাঁও"}
];
