final List districtListJson = [
  {"id": 28, "name": "Bagerhat - বাগেরহাট"},
  {"id": 11, "name": "Bandarban - বান্দরবন"},
  {"id": 35, "name": "Barguna - বরগুনা"},
  {"id": 33, "name": "Barisal - বরিশাল"},
  {"id": 34, "name": "Bhola - ভোলা"},
  {"id": 14, "name": "Bogura - বগুড়া "},
  {"id": 3, "name": "Brahmanbaria - ব্রাম্মন বাড়িয়া"},
  {"id": 6, "name": "Chandpur - চাদপুর"},
  {"id": 18, "name": "Chapainawabganj - চাপায় নব্বগন্জ"},
  {"id": 8, "name": "Chattogram - চট্টগ্রাম "},
  {"id": 24, "name": "Chuadanga - চুয়াডাঙ্গা "},
  {"id": 1, "name": "Comilla - কুমিল্লা "},
  {"id": 9, "name": "Coxsbazar - কক্সবাজার"},
  {"id": 47, "name": "Dhaka -  ঢাকা"},
  // {"id": 71, "name": "Dhaka-North - উত্তর ঢাকা"},
  // {"id": 72, "name": "Dhaka-South - দক্ষিন ঢাকা"},
  {"id": 75, "name": "Dhaka-City - ঢাকা শহর"},
  {"id": 54, "name": "Dinajpur - দিনাজপুর "},
  {"id": 52, "name": "Faridpur - ফরিদপুর "},
  {"id": 2, "name": "Feni - ফেনি"},
  {"id": 57, "name": "Gaibandha - গাইবান্ধা"},
  {"id": 41, "name": "Gazipur - গাজীপুর "},
  {"id": 51, "name": "Gopalganj - গোপালগঞ্জ "},
  {"id": 38, "name": "Habiganj - হবিগন্জ"},
  {"id": 63, "name": "Jamalpur - জামালপুর "},
  {"id": 20, "name": "Jashore - যশোর"},
  {"id": 30, "name": "Jhalakathi - ঝালুকাঠি "},
  {"id": 29, "name": "Jhenaidah - ঝিনাইদহ্"},
  {"id": 17, "name": "Joypurhat - জয়পুরহাট "},
  {"id": 10, "name": "Khagrachhari - খাগড়াছড়ি "},
  {"id": 27, "name": "Khulna - খুলনা "},
  {"id": 45, "name": "Kishoreganj - কিশোরগন্জ"},
  {"id": 60, "name": "Kurigram - কুড়িগ্রাম"},
  {"id": 25, "name": "Kushtia - কুষ্টিয়া "},
  {"id": 7, "name": "Lakshmipur - লক্ষীপুর"},
  {"id": 55, "name": "Lalmonirhat - লালমনিরহাট"},
  {"id": 50, "name": "Madaripur - মাদারীপুর "}, 
  {"id":26, "name": "Magura - মাগুরা "},
  {"id": 46, "name": "Manikganj - মানিকগঞ্জ "},
  {"id": 22, "name": "Meherpur - মেহেরপুর "},
  {"id": 37, "name": "Moulvibazar - মৌলবি বাজার"},
  {"id": 48, "name": "Munshiganj - মুন্সিগন্জ"},
  {"id": 62, "name": "Mymensingh - মেহেরপুর "},
  {"id": 19, "name": "Naogaon - নওগাঁ "},
  {"id": 23, "name": "Narail - নড়াইল "},
  {"id": 43, "name": "Narayanganj - নারায়ণগন্জ"},
  {"id": 40, "name": "Narsingdi - নরসিংদী "},
  {"id": 16, "name": "Natore - নাটোর"},
  {"id": 64, "name": "Netrokona - নেত্রকোনা "},
  {"id": 56, "name": "Nilphamari - নিলফামারীর "},
  {"id": 5, "name": "Noakhali - নোয়াখালী "},
  {"id": 13, "name": "Pabna - পাবনা "},
  {"id": 53, "name": "Panchagarh - পঞ্চগড় "},
  {"id": 31, "name": "Patuakhali - পটুয়াখালী "},
  {"id": 32, "name": "Pirojpur - পিরোজপুর "},
  {"id": 49, "name": "Rajabari - রাজবাড়ী "},
  {"id": 15, "name": "Rajshahi - রাজশাহী "},
  {"id": 4, "name": "Rangamati - রাঙ্গামাটি "},
  {"id": 59, "name": "Rangpur - রংপুর "},
  {"id": 21, "name": "Satkhira - সাতক্ষিরা "},
  {"id": 42, "name": "Shariatpur - শরিয়তপুর "},
  {"id": 61, "name": "Sherpur - শেরপুর "},
  {"id": 12, "name": "Sirajganj - সিরাজগঞ্জ "},
  {"id": 39, "name": "Sunamganj - সুনামগঞ্জ "},
  {"id": 36, "name": "Sylhet - সিলেট"},
  {"id": 44, "name": "Tangat - টাঙ্গাইল"},
  {"id": 58, "name": "Thakurgaon - ঠাকুরগাঁও"}
];