final List thanaListJson = [
  {"district_id": 72, "name": "AC Roy road/এ সি  রায় রোড "},
  {"district_id": 72, "name": "Abdul Hadi Lane/আব্দুল হাদি লেন "},
  {"district_id": 72, "name": "Abdul bani road/আব্দুল বাণী রোড "},
  {"district_id": 72, "name": "Abed Dali Road/আবেদ ডালি রোড "},
  {"district_id": 20, "name": "Abhaynagar/অভয়নগর "},
  {"district_id": 72, "name": "Abhidas Lane/অভিদাস লেন "},
  {"district_id": 72, "name": "Abul Hasnat Road/আবুল হাসনাত রোড "},
  {"district_id": 71, "name": "Abul Hotel Bus Stop/আবুল হোটেল বাস স্টপ "},
  {"district_id": 72, "name": "Abul hasnat lane/আবুল হাসনাত লেন "},
  {"district_id": 72, "name": "Abul khairat Road/আবুল খয়রাত রোড "},
  {"district_id": 72, "name": "Abul khairat Road/আবুল খয়রাত রোড "},
  {"district_id": 71, "name": "Adabor/আদাবর "},
  {"district_id": 14, "name": "Adamdighi/আদমদীঘি "},
  {"district_id": 71, "name": "Adarsha Bag/আদর্শ ব্যাগ "},
  {"district_id": 55, "name": "Aditmari/আদিতমারী "},
  {"district_id": 71, "name": "Aftab nagar/আফতাব নাগার "},
  {"district_id": 72, "name": "Aga sadek road/এগ সাদেক রোড "},
  {"district_id": 33, "name": "Agailjhara/আগাইলঝাড়া "},
  {"district_id": 72, "name": "Agamasi Lane/আগামাসি লেন "},
  {"district_id": 71, "name": "Agargaon/আগারগাঁও"},
  {"district_id": 71, "name": "Ahmed Nagar/আহমেদ নগর "},
  {"district_id": 72, "name": "Ahmedbagh/আহমেদবাগ "},
  {"district_id": 72, "name": "Ahsan Ullah Road/ আহসান উল্লা রোড "},
  {"district_id": 38, "name": "Ajmiriganj/আজমিরীগঞ্জ "},
  {"district_id": 71, "name": "Ajompur/আজমপুর "},
  {"district_id": 3, "name": "Akhaura/আখাউড়া "},
  {"district_id": 17, "name": "Akkelpur/আক্কেলপুর "},
  {"district_id": 72, "name": "Akshay Das Lane/অক্ষয় দাস লেন "},
  {"district_id": 72, "name": "Al Amin Road/আল আমিন রোড "},
  {"district_id": 24, "name": "Alamdanga/আলমগংগা "},
  {"district_id": 72, "name": "Alamganj Road/আলামগঞ্জ রোড "},
  {"district_id": 52, "name": "Alfadanga/আলফাডাঙ্গা "},
  {"district_id": 72, "name": "Ali hossain Khan lane/আলী হোসাইন খান লেন "},
  {"district_id": 11, "name": "Alikadam/আলীকদম "},
  {
    "district_id": 72,
    "name": "Aminabad colony moghbaraz/আমিনাবাদ কলোনী মোঘলবাজার "
  },
  {"district_id": 72, "name": "Aminbagh/আমিনবাগ "},
  {"district_id": 35, "name": "Amtali/আমতলী "},
  {"district_id": 71, "name": "Ananda Nagar/আনন্দ নগর "},
  {"district_id": 72, "name": "Anond mohan boshak Lane/আনন্দ মহান বসাক লেন"},
  {"district_id": 8, "name": "Anwara/আনোয়ারা"},
  {"district_id": 71, "name": "Apollo Hospital/অ্যাপোলো হাসপাতাল "},
  {"district_id": 43, "name": "Araihazar/আড়াইহাজার "},
  {"district_id": 72, "name": "Arambagh/আরামবাগ "},
  {"district_id": 71, "name": "Arjat Para/অর্জাত পাড়া"},
  {"district_id": 71, "name": "Armanitola/আরমানিতলা "},
  {"district_id": 72, "name": "Armenium Street/আর্মেনিয়াম স্ট্রিট "},
  {"district_id": 71, "name": "Army Stadium/আর্মি স্টেডিয়াম "},
  {"district_id": 71, "name": "Asad Gate/আসাদ গেট "},
  {"district_id": 71, "name": "Ashalota/আশালতা "},
  {"district_id": 72, "name": "Ashik lane/আশিক লেন "},
  {"district_id": 71, "name": "Ashkona/আশকোনা "},
  {"district_id": 3, "name": "Ashuganj/আশুগঞ্জ "},
  {"district_id": 21, "name": "Assasuni/আশাশুনি "},
  {"district_id": 13, "name": "Atghoria/আটঘরিয়া "},
  {"district_id": 64, "name": "Atpara/আটপাড়া "},
  {"district_id": 19, "name": "Atrai/আত্রাই "},
  {"district_id": 53, "name": "Atwari/আটোয়ারী "},
  {"district_id": 45, "name": "Austagram/অষ্টগ্রাম "},
  {
    "district_id": 72,
    "name": "Ayub Ali colony Rahim square/আয়ুব আলী কলোনী রাহিম স্কয়ার "
  },
  {"district_id": 72, "name": "Azimpur/আজিমপুর "},
  {"district_id": 72, "name": "Azizullah Road/আজিজুল্লাহ রোড "},
  {"district_id": 72, "name": "BDR Pilkhana/বি,ডি,আর, পিলখানা "},
  {"district_id": 72, "name": "BK Roy Lane/বি,কে রায় লেন "},
  {"district_id": 33, "name": "Babuganj/বাবুগঞ্জ "},
  {"district_id": 19, "name": "Badalgachi/বদলগাছী "},
  {"district_id": 59, "name": "Badargonj/বদরগঞ্জ "},
  {"district_id": 71, "name": "Badda/বাড্ডা "},
  {"district_id": 71, "name": "Badda Hossain Market/বাড্ডা হাসাইন মার্কেট "},
  {"district_id": 72, "name": "Badhika boshak Lane/বাধিকা বসাক লেন "},
  {"district_id": 72, "name": "Bagamganj Lane/বেগমগঞ্জ লেন "},
  {"district_id": 16, "name": "Bagatipara/বাগাতিপাড়া "},
  {"district_id": 71, "name": "Bagbari/বাগবাড়ি "},
  {"district_id": 72, "name": "Bagdasa Lane/বাগডাসা লেন "},
  {"district_id": 28, "name": "Bagerhat Sadar/বাগেরহাট সদর "},
  {"district_id": 15, "name": "Bagha/বাঘা "},
  {"district_id": 4, "name": "Baghaichari/বাঘাইছড়ি "},
  {"district_id": 20, "name": "Bagherpara/বাঘেরপাড়া "},
  {"district_id": 15, "name": "Bagmara/বাগমারা "},
  {"district_id": 72, "name": "Bahadurpur Lane/বাহাদুরপুর লেন "},
  {"district_id": 38, "name": "Bahubal/বাহুবল "},
  {"district_id": 72, "name": "Bailey Square Moghbazar/বেইলি স্কয়ার মগবাজার "},
  {"district_id": 71, "name": "Baily Road/বিলি রোড "},
  {
    "district_id": 72,
    "name": "Baitul Mukarram Stadium/বায়তুল মুকাররম স্টেডিয়াম "
  },
  {"district_id": 45, "name": "Bajitpur/বাজিতপুর "},
  {"district_id": 33, "name": "Bakerganj/বাকেরগঞ্জ "},
  {"district_id": 72, "name": "Bakshibagh/বাকশীবাগঃ "},
  {"district_id": 36, "name": "Balaganj/বালাগঞ্জ "},
  {"district_id": 58, "name": "Baliadangi/বালিয়াডাঙ্গী "},
  {"district_id": 49, "name": "Baliakandi/বালিয়াকান্দি "},
  {"district_id": 35, "name": "Bamna/বামনা "},
  {"district_id": 71, "name": "Banani Bus Stand/বনানী বাস স্ট্যান্ড "},
  {"district_id": 71, "name": "Banani DOHS/বনানী ডি,ও,এইচ,এস"},
  {"district_id": 71, "name": "Banani Graveyard/বনানী গ্রাভ্যার্ড "},
  {
    "district_id": 71,
    "name": "Banani Naval Head Quarter/বনানী নেভাল হেড কোয়ার্টার "
  },
  {"district_id": 71, "name": "Banani Road No. 1 - 11/বনানী রোড নো ১-১১"},
  {"district_id": 71, "name": "Banani Road No. 12 - 19/বনানী রোড নো ১২-১৯"},
  {"district_id": 71, "name": "Banani Road No. 20 - 28/বনানী রোড নো ২০-২৮"},
  {"district_id": 33, "name": "Banaripara/বানারীপাড়া "},
  {"district_id": 72, "name": "Banasree/বনশ্রী "},
  {"district_id": 71, "name": "Banasree Block A/বনশ্রী ব্লক এ "},
  {"district_id": 71, "name": "Banasree Block C/বনশ্রী ব্লক সি "},
  {"district_id": 71, "name": "Banasree Block D/বনশ্রী ব্লক ডি"},
  {"district_id": 71, "name": "Banasree Block E/বনশ্রী ব্লক ই"},
  {"district_id": 71, "name": "Banasree Block J/বনশ্রী ব্লক যে"},
  {"district_id": 71, "name": "Banasree Block K/বনশ্রী ব্লক কে "},
  {"district_id": 3, "name": "Bancharampur/বানচারামপুর "},
  {"district_id": 43, "name": "Bandar/বান্দার "},
  {"district_id": 11, "name": "Bandarban Sadar/বান্দারবান সদর "},
  {
    "district_id": 72,
    "name": "Bangabandhu Avenue & Rest House/বাংগাবান্ধা এভিনিউ এবং রেস্ট হাউজ"
  },
  {"district_id": 72, "name": "Bangabhaban/বংগভোবন "},
  {"district_id": 72, "name": "Bangladesh Bank Colony/বাংলাদেশ ব্যাঙ্ক কলোনী "},
  {
    "district_id": 72,
    "name": "Bangladesh Railway Barracks/বাংলাদেশ রেলওয়ে ব্যারার্কস "
  },
  {"district_id": 72, "name": "Bangshal/বংশাল "},
  {"district_id": 72, "name": "Bangshal Road/বংশসল রোড "},
  {"district_id": 38, "name": "Baniachong/বানিয়াচং "},
  {"district_id": 8, "name": "Banshkhali/বাঁশখালীর "},
  {"district_id": 16, "name": "Baraigram/বড়াইগ্রাম "},
  {"district_id": 35, "name": "Barguna Sadar/বরগুনা সদর "},
  {"district_id": 64, "name": "Barhatta/বারহাট্টা "},
  {"district_id": 71, "name": "Baridhara/বাড়িভাড়া "},
  {"district_id": 71, "name": "Baridhara DOHS/বারিধারা ডি,ও,এইচ,এস "},
  {"district_id": 33, "name": "Barisal Sadar/বরিশাল সদর "},
  {"district_id": 4, "name": "Barkal/বারকাল "},
  {"district_id": 37, "name": "Barlekha/বারলেকখা "},
  {"district_id": 71, "name": "Barontek/বাড়ন্তেক "},
  {"district_id": 1, "name": "Barura/বরুড়া "},
  {"district_id": 72, "name": "Basabo/বাসাবো "},
  {"district_id": 44, "name": "Basail/বাসাইল "},
  {"district_id": 72, "name": "Bashabo Ohaba Colony/বাসাবো ওহাব কলোনী "},
  {"district_id": 72, "name": "Bashir uddin road/বাঁশির উদ্দিন রোড "},
  {"district_id": 71, "name": "Bashtola/বাঁশতলা "},
  {"district_id": 71, "name": "Bashundhara/বসুন্ধরা "},
  {"district_id": 71, "name": "Bashundhara/বসুন্ধরা "},
  {"district_id": 71, "name": "Bashundhara Block A/বসুন্ধরা ব্লক এ "},
  {"district_id": 71, "name": "Bashundhara Block B/বসুন্ধরা ব্লক বি"},
  {"district_id": 71, "name": "Bashundhara Block C/বসুন্ধরা ব্লক সি"},
  {"district_id": 71, "name": "Bashundhara Block D/বসুন্ধরা ব্লক ডি"},
  {"district_id": 71, "name": "Bashundhara Block F/বসুন্ধরা ব্লক এফ"},
  {"district_id": 71, "name": "Bashundhara Block H/বসুন্ধরা ব্লক এইচ"},
  {"district_id": 71, "name": "Bashundhara Block I/বসুন্ধরা ব্লক আই"},
  {"district_id": 71, "name": "Bashundhara Bus Stand/বসুন্ধরা বাস স্ট্যান্ড "},
  {"district_id": 72, "name": "Bashundhara City/বসুন্ধরা সিটি "},
  {"district_id": 72, "name": "Basu Bazar Lane/বসু বাজার লেন "},
  {"district_id": 71, "name": "Baunia/বাউনিয়া "},
  {"district_id": 31, "name": "Bauphal/বাউফল "},
  {"district_id": 71, "name": "Bawlia Para/বাউলিয়া পাড়া "},
  {"district_id": 71, "name": "Bawneabad Area/বাওনেয়াবাদ এরিয়া "},
  {"district_id": 36, "name": "Beanibazar/বিয়ানীবাজার "},
  {"district_id": 72, "name": "Begum Bazar/বেগম বাজার "},
  {"district_id": 5, "name": "Begumganj/বেগমগঞ্জ "},
  {"district_id": 71, "name": "Begunbari/বেগুনবাড়ি "},
  {"district_id": 40, "name": "Belabo/বেলাব "},
  {"district_id": 4, "name": "Belaichari/বেলাইচারি "},
  {"district_id": 12, "name": "Belkuchi/বেলকুচি "},
  {"district_id": 71, "name": "Bepari Bari/বেপারী বাড়ি "},
  {"district_id": 13, "name": "Bera/বেড়া "},
  {"district_id": 35, "name": "Betagi/বেতাগী "},
  {"district_id": 72, "name": "Bhagwati Banerjee Road /ভগবতী ব্যানার্জী রোড "},
  {"district_id": 45, "name": "Bhairab/ভৈরব "},
  {"district_id": 62, "name": "Bhaluka/ভালুকা "},
  {"district_id": 32, "name": "Bhandaria/ভান্ডারিয়া "},
  {"district_id": 52, "name": "Bhanga/ভাঙা "},
  {"district_id": 13, "name": "Bhangura/ভাঙ্গুড়া "},
  {"district_id": 42, "name": "Bhedarganj/ভান্ডারগঞ্জ "},
  {"district_id": 25, "name": "Bheramara/ভেডারমারা "},
  {"district_id": 72, "name": "Bhojhari Saha Street/ভজহরি সাহা স্ট্রিট "},
  {"district_id": 34, "name": "Bhola Sadar/ভোলা সদর "},
  {"district_id": 18, "name": "Bholahat/ভোলাহাট "},
  {"district_id": 44, "name": "Bhuapur/ভুয়াপুর "},
  {"district_id": 60, "name": "Bhurungamari/ভুরুঙ্গামারী "},
  {"district_id": 71, "name": "Bhuyia Para/ভূঁইয়া পাড়া"},
  {"district_id": 72, "name": "Bijoy Nagar/বিজয় নগর "},
  {"district_id": 3, "name": "Bijoynagar/বিজয়নগর "},
  {"district_id": 54, "name": "Birampur/বিরামপুর "},
  {"district_id": 54, "name": "Birganj/বীরগঞ্জ "},
  {"district_id": 54, "name": "Birol/বিরল "},
  {"district_id": 71, "name": "Bishteki/বিশটেকি "},
  {"district_id": 39, "name": "Bishwambarpur/বিশ্বম্বরপুর "},
  {"district_id": 36, "name": "Bishwanath/বিশ্বনাথ "},
  {"district_id": 8, "name": "Boalkhali/বোয়াখালী "},
  {"district_id": 52, "name": "Boalmari/বোয়ালমারী "},
  {"district_id": 54, "name": "Bochaganj/বোচাগঞ্জ "},
  {"district_id": 53, "name": "Boda/বোদা "},
  {"district_id": 14, "name": "Bogura Sadar/বগুড়া সদর "},
  {"district_id": 63, "name": "Bokshiganj/বকশীগঞ্জ "},
  {"district_id": 71, "name": "Bonolota/বনলতা "},
  {"district_id": 34, "name": "Borhan Sddin/বোরহান সদ্দিন "},
  {"district_id": 27, "name": "Botiaghata/বটিয়াঘাটা "},
  {"district_id": 71, "name": "Box Nagar/বাক্স নগর "},
  {"district_id": 3, "name": "Brahmanbaria Sadar/ব্রাহ্মণবাড়িয়া সদর "},
  {"district_id": 1, "name": "Brahmanpara/ব্রাহ্মণপাড়া "},
  {"district_id": 1, "name": "Burichang/বুড়িচং"},
  {"district_id": 71, "name": "CDH Shampan/সি,এইচ,ডি, সাম্পান "},
  {"district_id": 72, "name": "Central prison/সেন্ট্রাল প্রিন্স"},
  {"district_id": 71, "name": "Chairman bari/চেয়ারম্যান বাড়ি "},
  {"district_id": 9, "name": "Chakaria/চকরিয়া "},
  {"district_id": 72, "name": "Chamelibagh/চামেলিবাঘ "},
  {"district_id": 72, "name": "Champatli lane/চাম্পাতলী লেন "},
  {"district_id": 8, "name": "Chandanaish/চন্দনাইশ "},
  {
    "district_id": 72,
    "name": "Chandi Charan Bose Street/চান্দি ছাড়ান বসি স্ট্রিট "
  },
  {"district_id": 1, "name": "Chandina/চান্দিনা "},
  {"district_id": 6, "name": "Chandpur Sadar/চাঁদপুর সদর "},
  {"district_id": 72, "name": "Chankharpul lane/চানখারপুল লেন "},
  {"district_id": 18, "name": "Chapainawabganj Sadar/চাঁপাইনবাবগঞ্জ সদর "},
  {"district_id": 52, "name": "Charbhadrasan/চরভদ্রাসন "},
  {"district_id": 34, "name": "Charfesson/চারফেসসন "},
  {"district_id": 15, "name": "Charghat/চারঘাট "},
  {"district_id": 60, "name": "Charrajibpur/চাররাজিবপুর "},
  {"district_id": 5, "name": "Chatkhil/চাটখিল"},
  {"district_id": 13, "name": "Chatmohar/চাটমোহর "},
  {"district_id": 1, "name": "Chauddagram/চৌদ্দগ্রাম "},
  {"district_id": 12, "name": "Chauhali/চৌহালী "},
  {"district_id": 72, "name": "Chawk Bazar/চাওক বাজার "},
  {"district_id": 2, "name": "Chhagalnaiya/ছাগলনাইয়া "},
  {"district_id": 39, "name": "Chhatak/ছাতক "},
  {"district_id": 60, "name": "Chilmari/চিলমারী "},
  {"district_id": 54, "name": "Chirirbandar/চিরিরবন্দর "},
  {"district_id": 28, "name": "Chitalmari/চিতলমারী "},
  {"district_id": 71, "name": "Chittagong Road/চিটাগাং রোড "},
  {"district_id": 72, "name": "Chota Katra/ছোট কাটরা "},
  {"district_id": 20, "name": "Chougachha/চৌগাছা "},
  {"district_id": 24, "name": "Chuadanga Sadar/চুয়াডাঙ্গা সদর "},
  {"district_id": 38, "name": "Chunarughat/চুনারুঘাট "},
  {"district_id": 72, "name": "Circular Road/সার্কুলার রোড "},
  {"district_id": 71, "name": "Coca Cola Bus Stop/কোকা কোলা বাস স্টপ "},
  {"district_id": 1, "name": "Comilla Sadar/কুমিল্লা সদর "},
  {"district_id": 72, "name": "Committee ganj/কমিটি গঞ্জ "},
  {"district_id": 5, "name": "Companiganj/কোম্পানীগঞ্জ "},
  {"district_id": 36, "name": "Companiganj/কোম্পানীগঞ্জ "},
  {"district_id": 71, "name": "Confidence Shopping Mall/কনফিডেন্স শপিং মল "},
  {"district_id": 72, "name": "Court House Street/কোর্ট হাউস স্ট্রিট "},
  {"district_id": 9, "name": "Coxsbazar-Sadar/ক্সসবাজার -সদর "},
  {"district_id": 72, "name": "D.C Court/ডি,সি কোর্ট "},
  {"district_id": 72, "name": "DC Roy Road/ডিসি রায় রোড "},
  {"district_id": 2, "name": "Daganbhuiyan/দাগনভূইয়াঁ "},
  {"district_id": 27, "name": "Dakop/দাকোপ "},
  {"district_id": 71, "name": "Dakshinkhan/দক্ষিণখান "},
  {"district_id": 36, "name": "Dakshinsurma/দক্ষিণসুরমা "},
  {"district_id": 42, "name": "Damudya/ডামুড্যা "},
  {"district_id": 24, "name": "Damurhuda/দামুড়হুদা "},
  {"district_id": 71, "name": "Darus Salam/দ্বারুশ সালাম "},
  {"district_id": 31, "name": "Dashmina/দশমিনি "},
  {"district_id": 1, "name": "Daudkandi/দাউদকান্দি "},
  {"district_id": 25, "name": "Daulatpur/দৌলতপুর "},
  {"district_id": 72, "name": "Dayaganj Jelepara/দয়াগঞ্জ জেলেপাড়া "},
  {"district_id": 72, "name": "Dayaganj Road/দয়াগঞ্জ রোড "},
  {"district_id": 21, "name": "Debhata/দেবহাটা "},
  {"district_id": 1, "name": "Debidwar/দেবিদ্বার "},
  {"district_id": 53, "name": "Debiganj/দেবীগঞ্জ "},
  {"district_id": 72, "name": "Deen Nath Sen Road/দ্বীন নাথ রোড "},
  {"district_id": 44, "name": "Delduar/দেলদুয়ার "},
  {"district_id": 72, "name": "Demra/ডেমরা "},
  {"district_id": 39, "name": "Derai/ডেরায় "},
  {"district_id": 72, "name": "Devidas Ghat Lane/ডেভিডস ঘাট লেন "},
  {"district_id": 63, "name": "Dewangonj/দেওয়ানগঞ্জ "},
  {"district_id": 71, "name": "Dhaka - Cantonment/ঢাকা- ক্যান্টনমেন্ট "},
  {
    "district_id": 71,
    "name":
        "Dhaka - North City Corporation Market/ঢাকা -নর্থ সিটি কর্পোরেশন মার্কেট "
  },
  {"district_id": 72, "name": "Dhaka Cotton Mills/ ঢাকা কটন মিলস "},
  {"district_id": 72, "name": "Dhaka University/ঢাকা ইউনিভার্সিটি "},
  {"district_id": 72, "name": "Dhaka medical college/ঢাকা মেডিকেল কলেজ "},
  {"district_id": 72, "name": "Dhalkanagar Lane/ঢালকানাগার লেন "},
  {"district_id": 72, "name": "Dhalpur/ধালপুর "},
  {"district_id": 19, "name": "Dhamoirhat/ধামইরহাট "},
  {"district_id": 47, "name": "Dhamrai/ধামরাই "},
  {"district_id": 71, "name": "Dhamrai/ধামরাই "},
  {"district_id": 44, "name": "Dhanbari/ধামরাই "},
  {
    "district_id": 72,
    "name": "Dhanmondi - Road No. 1 - 10/ধানমন্ডি -রোড নং১-১০"
  },
  {"district_id": 72, "name": "Dhanmondi 1/Dhanmondi/ধানমন্ডি 1/ধানমন্ডি "},
  {"district_id": 72, "name": "Dhanmondi 10/ধানমন্ডি ১০"},
  {"district_id": 72, "name": "Dhanmondi 10A/ধানমন্ডি ১০ এ  "},
  {"district_id": 72, "name": "Dhanmondi 11/ধানমন্ডি ১১"},
  {"district_id": 72, "name": "Dhanmondi 11A/ধানমন্ডি ১১ এ "},
  {"district_id": 72, "name": "Dhanmondi 12/ধানমন্ডি ১২"},
  {"district_id": 72, "name": "Dhanmondi 12A/ধানমন্ডি ১২ এ "},
  {"district_id": 72, "name": "Dhanmondi 13/ধানমন্ডি ১৩"},
  {"district_id": 72, "name": "Dhanmondi 13A/ধানমন্ডি ১৩ এ "},
  {"district_id": 72, "name": "Dhanmondi 14/ধানমন্ডি ১৪"},
  {"district_id": 72, "name": "Dhanmondi 15/ধানমন্ডি ১৫"},
  {"district_id": 72, "name": "Dhanmondi 16/ধানমন্ডি ১৬"},
  {"district_id": 72, "name": "Dhanmondi 17/ধানমন্ডি ১৭"},
  {"district_id": 72, "name": "Dhanmondi 18/ধানমন্ডি ১৮"},
  {"district_id": 72, "name": "Dhanmondi 19/ধানমন্ডি ১৯"},
  {"district_id": 72, "name": "Dhanmondi 1A/ধানমন্ডি ১ এ "},
  {"district_id": 72, "name": "Dhanmondi 2/ধানমন্ডি ২"},
  {"district_id": 72, "name": "Dhanmondi 20/ধানমন্ডি ২০"},
  {"district_id": 72, "name": "Dhanmondi 21/ধানমন্ডি ২১"},
  {"district_id": 72, "name": "Dhanmondi 22/ধানমন্ডি ২২"},
  {"district_id": 72, "name": "Dhanmondi 23/ধানমন্ডি ২৩"},
  {"district_id": 72, "name": "Dhanmondi 24/ধানমন্ডি ২৪"},
  {"district_id": 72, "name": "Dhanmondi 25/ধানমন্ডি ২৫"},
  {"district_id": 72, "name": "Dhanmondi 26/ধানমন্ডি ২৬"},
  {"district_id": 72, "name": "Dhanmondi 27/ধানমন্ডি ২৭"},
  {"district_id": 72, "name": "Dhanmondi 28/ধানমন্ডি ২৮"},
  {"district_id": 72, "name": "Dhanmondi 29/ধানমন্ডি ২৯"},
  {"district_id": 72, "name": "Dhanmondi 2A/ধানমন্ডি ২ এ "},
  {"district_id": 72, "name": "Dhanmondi 3/সানমন্ডি ৩"},
  {"district_id": 72, "name": "Dhanmondi 30/ধানমন্ডি ৩০"},
  {"district_id": 72, "name": "Dhanmondi 31/ধানমন্ডি ৩১"},
  {"district_id": 72, "name": "Dhanmondi 32/ধানমন্ডি ৩২"},
  {"district_id": 72, "name": "Dhanmondi 3A/ধানমন্ডি ৩ এ "},
  {"district_id": 72, "name": "Dhanmondi 4/ধানমন্ডি ৪"},
  {"district_id": 72, "name": "Dhanmondi 4A/ধানমন্ডি ৪ এ "},
  {"district_id": 72, "name": "Dhanmondi 5/ধানমন্ডি ৫"},
  {"district_id": 72, "name": "Dhanmondi 5A/ধানমন্ডি ৫ এ "},
  {"district_id": 72, "name": "Dhanmondi 6/ধানমন্ডি ৬"},
  {"district_id": 72, "name": "Dhanmondi 6A/ধানমন্ডি ৬ এ "},
  {"district_id": 72, "name": "Dhanmondi 7/ধানমন্ডি ৭"},
  {"district_id": 72, "name": "Dhanmondi 7A/ধানমন্ডি ৭ এ "},
  {"district_id": 72, "name": "Dhanmondi 8/ধানমন্ডি ৮"},
  {"district_id": 72, "name": "Dhanmondi 8A/ধানমন্ডি ৮ এ "},
  {"district_id": 72, "name": "Dhanmondi 9/ধানমন্ডি ৯"},
  {"district_id": 72, "name": "Dhanmondi 9A/ধানমন্ডি ৯ এ "},
  {
    "district_id": 72,
    "name": "Dhanmondi Road No. 11 - 16/ধানমন্ডি রোড নো ১১-১৬"
  },
  {
    "district_id": 72,
    "name": "Dhanmondi Road No. 1A - 13A/ধানমন্ডি রোড নো ১ এ -১৩ এ "
  },
  {
    "district_id": 72,
    "name": "Dhanmondi Staff Quarter/ধানমন্ডি স্টাফ কোয়ার্টার "
  },
  {"district_id": 39, "name": "Dharmapasha/ধর্মপাশা "},
  {"district_id": 62, "name": "Dhobaura/ধোবাউড়া "},
  {"district_id": 72, "name": "Dholaipar/ধোলাইপাড় "},
  {"district_id": 14, "name": "Dhunot/ধুনট "},
  {"district_id": 71, "name": "Diabari/দিয়াবাড়ি "},
  {"district_id": 10, "name": "Dighinala/দীঘিনালা "},
  {"district_id": 27, "name": "Digholia/দীঘোলিয়া "},
  {"district_id": 72, "name": "Digu Babu Lane/দ্বিগু বাবু লেন "},
  {"district_id": 72, "name": "Dilkusha/দিলকুশা "},
  {
    "district_id": 72,
    "name": "Dilkusha Commercial Area/দিলকুশা কর্মাশিয়াল এরিয়া "
  },
  {"district_id": 56, "name": "Dimla/ডিমলা "},
  {"district_id": 54, "name": "Dinajpur Sadar/দিনাজপুর সদর "},
  {"district_id": 71, "name": "Doctor Goli/ডাক্তার গলি "},
  {"district_id": 47, "name": "Dohar/দোহার "},
  {"district_id": 71, "name": "Dokkhingao/দক্ষিণগাঁও "},
  {"district_id": 56, "name": "Domar/ডোমার "},
  {"district_id": 34, "name": "Doulatkhan/দৌলতখান "},
  {"district_id": 46, "name": "Doulatpur/দৌলতপুর "},
  {"district_id": 39, "name": "Dowarabazar/দোয়ারাবাজার "},
  {"district_id": 72, "name": "Dr. M A Rashid Hall/ডা.এম, এ, রাশিদ হল "},
  {"district_id": 31, "name": "Dumki/দুমকি "},
  {"district_id": 27, "name": "Dumuria/ডুমুরিয়া "},
  {"district_id": 14, "name": "Dupchanchia/দুপচাঁচিয়া "},
  {"district_id": 15, "name": "Durgapur/দুর্গাপুর "},
  {"district_id": 64, "name": "Durgapur/দুর্গাপুর "},
  {"district_id": 72, "name": "East Bashabo/পূর্ব বাসাবো "},
  {"district_id": 71, "name": "East Hazipara/পূর্ব হাজিপাড়া "},
  {"district_id": 71, "name": "East Merul Badda/পূর্ব মেরুল বাড্ডা "},
  {"district_id": 71, "name": "East Nakhalpara/পূর্ব নাখালপাড়া "},
  {"district_id": 71, "name": "East Nurerchala/পূর্ব নুরেরচালা "},
  {"district_id": 72, "name": "East Raibazar/পূর্ব  রাইবাজার "},
  {"district_id": 71, "name": "East Rampura/পূর্ব রামপুরা "},
  {"district_id": 72, "name": "Eastern Housing/ইস্টার্ন হাউসিং "},
  {"district_id": 72, "name": "Elephant Road/এলিফ্যান্ট রোড "},
  {
    "district_id": 72,
    "name":
        "Engineering University & Residential Area/এঞ্জিনীরিং ইউনিভার্সিটি &রেসিডেন্সিয়াল এরিয়া "
  },
  {"district_id": 72, "name": "English Road/ইংলিশ রোড "},
  {"district_id": 72, "name": "Eskaton Garden Road/ইস্কাটন গার্ডেন রোড "},
  {"district_id": 72, "name": "Fakirapul/ফকিরাপুল "},
  {"district_id": 72, "name": "Fakirapul Market Area/ফকিরাপুল মার্কেট এরিয়া "},
  {"district_id": 28, "name": "Fakirhat/ফকিরহাট "},
  {"district_id": 72, "name": "Farashgang Lane/ফরাশগঞ্জ লেন "},
  {"district_id": 72, "name": "Faridabad Lane/ফরিদাবাদ লেন "},
  {"district_id": 6, "name": "Faridgonj/ফরিদগঞ্জ "},
  {"district_id": 13, "name": "Faridpur /ফরিদপুর "},
  {"district_id": 52, "name": "Faridpur Sadar/ফরিদপুর সদর "},
  {"district_id": 71, "name": "Farmgate/ফার্মগেটে "},
  {"district_id": 8, "name": "Fatikchhari/ফটিকছড়ি "},
  {"district_id": 36, "name": "Fenchuganj/ফেঞ্চুগঞ্জ "},
  {"district_id": 2, "name": "Feni Sadar/ফেনী সদর "},
  {"district_id": 72, "name": "Folder Street/ফ্রেঞ্চ স্ট্রিট "},
  {"district_id": 72, "name": "French Road/ফ্রেঞ্চ রোড "},
  {"district_id": 54, "name": "Fulbari/ফুলবাড়ী "},
  {"district_id": 62, "name": "Fulbaria/ফুলবাড়ীয়া "},
  {
    "district_id": 72,
    "name": "Fulbaria Station East Area/ ফুলবাড়ীয়া স্টেশন ইস্ট এরিয়া "
  },
  {"district_id": 2, "name": "Fulgazi/ফুলগাজী "},
  {"district_id": 27, "name": "Fultola/ফুলতলা "},
  {"district_id": 14, "name": "Gabtali/গাবতলী "},
  {"district_id": 71, "name": "Gabtoli Bus Terminal/গাবতলী বাস টার্মিনাল "},
  {"district_id": 62, "name": "Gafargaon/গাফারগঞ্জ "},
  {"district_id": 57, "name": "Gaibandha Sadar/গাইবান্ধা সদর "},
  {"district_id": 48, "name": "Gajaria/গজারিয়া "},
  {"district_id": 31, "name": "Galachipa/গলাচিপা "},
  {"district_id": 59, "name": "Gangachara/গঙ্গাচড়া "},
  {"district_id": 22, "name": "Gangni/গাংনী "},
  {"district_id": 72, "name": "Ganguly Lane/গাঙ্গুলী লেন "},
  {"district_id": 41, "name": "Gazipur Sadar/গাজীপুর সদর "},
  {"district_id": 72, "name": "Gendaria/গেন্ডারিয়া "},
  {"district_id": 72, "name": "Ghaji Osman Gani Road/গাজী ওসমান  গনি রোড "},
  {"district_id": 44, "name": "Ghatail/ঘাটাইল "},
  {"district_id": 54, "name": "Ghoraghat/ঘোড়াঘাট "},
  {"district_id": 46, "name": "Gior/জিওর "},
  {"district_id": 49, "name": "Goalanda/গোয়ালন্দ "},
  {"district_id": 57, "name": "Gobindaganj/গোবিন্দগঞ্জ "},
  {"district_id": 15, "name": "Godagari/গোদাগাড়ী "},
  {"district_id": 72, "name": "Golakpal Lane/গোলাকপাল লেন "},
  {"district_id": 72, "name": "Golam Mostafa Lane/গোলাম মোস্তফা লেন "},
  {"district_id": 36, "name": "Golapganj/গোলাপগঞ্জ "},
  {"district_id": 71, "name": "Golartek/গোলার্তেক "},
  {"district_id": 18, "name": "Gomostapur/গোমস্তাপুর "},
  {"district_id": 51, "name": "Gopalganj Sadar/গোপালগঞ্জ সদর "},
  {"district_id": 44, "name": "Gopalpur/গোপালপুর "},
  {"district_id": 72, "name": "Gopibagh/গোপীবাগঃ "},
  {
    "district_id": 72,
    "name": "Gopinath Dutt Kabiraj Street/গোপীনাথ দত্ত কবিরাজ স্ট্রেট "
  },
  {"district_id": 72, "name": "Goran/গোড়ান "},
  {"district_id": 71, "name": "Goran Tampoo stand/গোড়ান টেম্পো স্ট্যান্ড "},
  {"district_id": 42, "name": "Gosairhat/গোসাইরহাট "},
  {"district_id": 62, "name": "Gouripur/গৌরীপুর "},
  {"district_id": 33, "name": "Gournadi/গৌরনদী "},
  {"district_id": 72, "name": "Govinda das lane/গবিদ্যা দাস লেন "},
  {"district_id": 36, "name": "Gowainghat/গোয়াইনঘাট "},
  {"district_id": 72, "name": "Green Corner paribag/গ্রীন কর্নার পরীবাগ "},
  {"district_id": 72, "name": "Green Road East/পূর্ব গ্রীন রোড "},
  {
    "district_id": 72,
    "name": "Green Road Staff Quarter/গ্রীন রোড স্টাফ কোয়ার্টার "
  },
  {"district_id": 72, "name": "Green Road West/পশ্চিম  গ্রীন রোড "},
  {"district_id": 72, "name": "Green Square/গ্রীন স্কয়ার "},
  {
    "district_id": 72,
    "name": "Green corner green road/গ্রীন কর্নার গ্রীন রোড "
  },
  {"district_id": 10, "name": "Guimara/গুইমারা"},
  {"district_id": 72, "name": "Gulbagh/গুলবাঘ"},
  {"district_id": 72, "name": "Gulistan/গুলিস্তান "},
  {"district_id": 71, "name": "Gulshan 1/গুলশান ১"},
  {"district_id": 71, "name": "Gulshan 2/গুলশান ২"},
  {
    "district_id": 71,
    "name": "Gulshan Badda link Road/গুলশান বাড্ডা লিংক রোড "
  },
  {"district_id": 16, "name": "Gurudaspur/গুরদাসপুর"},
  {"district_id": 38, "name": "Habiganj Sadar/হবিগঞ্জ সদর "},
  {"district_id": 72, "name": "Hafiz Ullah Road/হাফিজ উল্লাহ রোড "},
  {"district_id": 6, "name": "Haimchar/হিমচর "},
  {"district_id": 72, "name": "Haji Afsaruddin Road/হাজি আফসারউদ্দিন রোড "},
  {
    "district_id": 72,
    "name": "Haji Mohammad Moshin Hall/হাজি মোহাম্মদ মোহাশিন হল "
  },
  {"district_id": 6, "name": "Hajiganj/হাজীগঞ্জ "},
  {
    "district_id": 72,
    "name": "Hakim Habibur Rahman Road/হেকিম হাবিবুর রহমান রোড "
  },
  {"district_id": 54, "name": "Hakimpur/হাকিমপুর "},
  {"district_id": 62, "name": "Haluaghat/হালুয়াঘাট "},
  {
    "district_id": 72,
    "name": "Hari Parashanna Mitra Road/হাড়ি পড়াশনা মিত্র রোড "
  },
  {"district_id": 72, "name": "Hari Street/হাড়ি স্ট্রেট "},
  {"district_id": 72, "name": "Haricharan Roy Road/হরিচরণ রায় রোড "},
  {"district_id": 29, "name": "Harinakundu/হরিণাকুন্ডু "},
  {"district_id": 58, "name": "Haripur/হরিপুর "},
  {"district_id": 46, "name": "Harirampur/হরিরামপুর "},
  {
    "district_id": 72,
    "name": "Harish chand lane basu s/হারিস চাঁদ লেন বসু এস "
  },
  {"district_id": 72, "name": "Hatembagh/হাতেমবাগ "},
  {"district_id": 8, "name": "Hathazari/হাটহাজারী "},
  {"district_id": 5, "name": "Hatia/হাতিয়া "},
  {"district_id": 55, "name": "Hatibandha/হাতীবান্ধা "},
  {"district_id": 71, "name": "Hatirjheel/হাতিরঝিল "},
  {
    "district_id": 72,
    "name": "Hatirpool Free school Street/হাতিরপুল ফ্রি স্কুল স্ট্রেট "
  },
  {"district_id": 72, "name": "Hatkhola Road/হাটখোলা রোড "},
  {"district_id": 72, "name": "Hazaribagh/হাজারীবাঘ "},
  {"district_id": 71, "name": "Hazi Camp/হাজি ক্যাম্প "},
  {"district_id": 72, "name": "Hazi mainuddin Road/হাজি মাইনুদ্দিন রোড "},
  {"district_id": 72, "name": "Hemendra das lane/হিমেন্দ্র দাস লেন "},
  {
    "district_id": 72,
    "name": "High court Staff quarter/হাই কোর্ট স্টাফ কোয়ার্টার "
  },
  {"district_id": 33, "name": "Hizla/হিজলা "},
  {"district_id": 1, "name": "Homna/হোমনা "},
  {"district_id": 45, "name": "Hossainpur/হোসাইনপুর "},
  {"district_id": 71, "name": "House Building/হাউস বিল্ডিং "},
  {"district_id": 71, "name": "ICDDRB/আই,সি,ডি,ডি,আর,বি "},
  {"district_id": 71, "name": "Ibrahimpur/ইব্রাহিমপুর "},
  {"district_id": 72, "name": "Imam Gang/এমাম গ্যাং "},
  {"district_id": 72, "name": "Indrapuri/ইন্দ্রপুরী "},
  {"district_id": 13, "name": "Ishwordi/ঈশ্বরদী "},
  {"district_id": 63, "name": "Islampur/লসলামপুর"},
  {"district_id": 72, "name": "Islampur/ইসলামপুর "},
  {"district_id": 62, "name": "Iswarganj/ঈশ্বরগঞ্জ "},
  {"district_id": 45, "name": "Itna/ইটনা "},
  {"district_id": 72, "name": "Jadab Narayandas lane/যাদব নারায়ণদাস লেন "},
  {"district_id": 72, "name": "Jagannath Hall/জগন্নাথ হল "},
  {"district_id": 39, "name": "Jagannathpur/জগন্নাথপুর "},
  {"district_id": 71, "name": "Jahangir Gate/জাহাঙ্গীর গেট "},
  {"district_id": 71, "name": "Jahurul Haque City/জহুরুল হক সিটি "},
  {"district_id": 36, "name": "Jaintiapur/জৈয়ন্তিপুর"},
  {"district_id": 56, "name": "Jaldhaka/জলঢাকা "},
  {"district_id": 39, "name": "Jamalganj/জামালগঞ্জ "},
  {"district_id": 63, "name": "Jamalpur Sadar/জামালপুর সদর "},
  {"district_id": 71, "name": "Jamuna Future Park/যমুনা ফিউচার পার্ক "},
  {"district_id": 71, "name": "Jashimuddin Road/জসিমউদ্দিন রোড "},
  {"district_id": 72, "name": "Jatrabari/যাত্রাবাড়ী "},
  {"district_id": 72, "name": "Jayakali Mandir Road/জয়কালী মন্দির রোড "},
  {"district_id": 20, "name": "Jessore Sadar/যশোর সদর "},
  {"district_id": 30, "name": "Jhalakathi Sadar/ঝালকাঠি সদর "},
  {"district_id": 29, "name": "Jhenaidah Sadar/ঝিনাইদাহ সদর "},
  {"district_id": 61, "name": "Jhenaigati/ঝিনাইগাতী "},
  {"district_id": 20, "name": "Jhikargacha/ঝিকরগাছা "},
  {"district_id": 24, "name": "Jibannagar/জীবননগর "},
  {"district_id": 71, "name": "Joar Shahara/জোরা সাহারা "},
  {"district_id": 72, "name": "Jorpool Lane/জোড়পুল লেন "},
  {"district_id": 17, "name": "Joypurhat Sadar/জয়পুরহাট সদর "},
  {"district_id": 72, "name": "Judge Court/জজ কোর্ট "},
  {"district_id": 72, "name": "Jumabali Lane/জুমাবলী লেন "},
  {"district_id": 72, "name": "Jumma Beppari Lane/জুম্মা বেপারী লেন "},
  {"district_id": 4, "name": "Juraichari/জুয়াড়িচড়ি"},
  {"district_id": 37, "name": "Juri/জুড়ি"},
  {
    "district_id": 72,
    "name": "Justice Lalmohon Das Lane/জাস্টিস্ লালমোহন দাস লেন "
  },
  {"district_id": 72, "name": "K M Das Lane/কে, এম, দাস লেন "},
  {"district_id": 72, "name": "K.M Azam Lane/কে, এম, আজম লেন "},
  {"district_id": 72, "name": "K.Pk Ghosh Street/কে,পিক ঘোষ স্ট্রেট "},
  {"district_id": 5, "name": "Kabirhat/কবিরহাট "},
  {"district_id": 6, "name": "Kachua/কচুয়া "},
  {"district_id": 28, "name": "Kachua/কচুয়া "},
  {"district_id": 72, "name": "Kadamtala/কদমতলা "},
  {"district_id": 71, "name": "Kafrul/কাফরুল "},
  {"district_id": 14, "name": "Kahaloo/কাহালু "},
  {"district_id": 54, "name": "Kaharol/কাহারোল "},
  {"district_id": 72, "name": "Kakrail/কাকরাইল "},
  {"district_id": 72, "name": "Kalabagan/কলাবাগান "},
  {
    "district_id": 72,
    "name": "Kalabagan Free School Street/কলাবাগান ফ্রি স্কুল স্ট্রেট "
  },
  {"district_id": 71, "name": "Kalachandpur/কালাচাঁদপুর "},
  {"district_id": 17, "name": "Kalai/কালাই "},
  {"district_id": 31, "name": "Kalapara/কলাপাড়া "},
  {"district_id": 21, "name": "Kalaroa/কলারোয়া "},
  {"district_id": 23, "name": "Kalia/কালিয়া "},
  {"district_id": 41, "name": "Kaliakair/কালিয়াকৈর "},
  {"district_id": 21, "name": "Kaliganj/কালিগঞ্জ "},
  {"district_id": 29, "name": "Kaliganj/কালীগঞ্জ "},
  {"district_id": 41, "name": "Kaliganj/কালীগঞ্জ "},
  {"district_id": 55, "name": "Kaliganj/কালীগঞ্জ "},
  {"district_id": 44, "name": "Kalihati/কালিহাতী "},
  {"district_id": 50, "name": "Kalkini/কালকিনি "},
  {"district_id": 71, "name": "Kallyanpur/কল্যাণপুর "},
  {"district_id": 64, "name": "Kalmakanda/কালমাকান্দা "},
  {"district_id": 49, "name": "Kalukhali/কালুখালী "},
  {"district_id": 72, "name": "Kamalapur/কমলাপুর "},
  {"district_id": 7, "name": "Kamalnagar/কামালনাগার "},
  {"district_id": 12, "name": "Kamarkhand/কামারখন্দ "},
  {"district_id": 72, "name": "Kamlapur/কমলাপুর"},
  {"district_id": 37, "name": "Kamolganj/কমলগঞ্জ"},
  {"district_id": 36, "name": "Kanaighat/কানাইঘাট "},
  {"district_id": 41, "name": "Kapasia/কাপাসিয়া "},
  {"district_id": 4, "name": "Kaptai/কাপ্তাই "},
  {"district_id": 45, "name": "Karimgonj/করিমগঞ্জ "},
  {"district_id": 72, "name": "Karimullarbagh/করিমুল্লারবাগ "},
  {"district_id": 8, "name": "Karnafuli/কর্ণফুলী "},
  {"district_id": 71, "name": "Karwan Bazar/কাওরন বাজার "},
  {"district_id": 72, "name": "Kasaituly/কাসাইটুলী "},
  {"district_id": 3, "name": "Kasba/কসবা"},
  {"district_id": 51, "name": "Kashiani/কাশিয়ানী "},
  {"district_id": 30, "name": "Kathalia/কাঠালিয়া "},
  {"district_id": 72, "name": "Katherpul Lane/কাঠেরপুল লেন "},
  {"district_id": 45, "name": "Katiadi/কটিয়াদী "},
  {"district_id": 59, "name": "Kaunia/কাউনিয়া "},
  {"district_id": 4, "name": "Kawkhali/কাউখালী "},
  {"district_id": 32, "name": "Kawkhali/কাউখালী "},
  {"district_id": 71, "name": "Kawranbazar/কাওরান বাজার "},
  {"district_id": 72, "name": "Kazi Zia uddin Lane/কাজী জিয়া উদ্দিন লেন "},
  {"district_id": 71, "name": "Kazipara/কাজিপাড়া "},
  {"district_id": 12, "name": "Kazipur/কাজিপুর "},
  {"district_id": 72, "name": "Kazirbagh/কাজিরবাগ "},
  {"district_id": 72, "name": "Kedar Nath/কেদার নাথ "},
  {"district_id": 64, "name": "Kendua/কেন্দুয়া "},
  {"district_id": 47, "name": "Keraniganj/কেনরানীগঞ্জ "},
  {"district_id": 72, "name": "Keraniganj Sadar/কেরানীগঞ্জ সদর "},
  {"district_id": 72, "name": "Keshab Banarjee Road/কেশব ব্যানার্জী রোড "},
  {"district_id": 20, "name": "Keshabpur/কেশাবোৰ "},
  {"district_id": 10, "name": "Khagrachhari Sadar/খাগড়াছড়ি সদর "},
  {"district_id": 64, "name": "Khaliajuri/খালিয়াজুরী "},
  {"district_id": 54, "name": "Khansama/খানসামা "},
  {"district_id": 17, "name": "Khetlal/ক্ষেতলাল "},
  {"district_id": 71, "name": "Khilgaon/খিলগাঁও "},
  {"district_id": 72, "name": "Khilgaon/খিলগাঁও"},
  {"district_id": 72, "name": "Khilgaon Bagicha/খিলগাঁও বাগিচা "},
  {"district_id": 72, "name": "Khilgaon Colony/খিলগাঁও কলনি "},
  {"district_id": 71, "name": "Khilgoan Bus stop/খিলগাঁ বাস স্টপ "},
  {"district_id": 71, "name": "Khilkhet/খিলক্ষের "},
  {"district_id": 25, "name": "Khoksa/খোকসা "},
  {"district_id": 45, "name": "Kishoreganj Sadar/কিশোরগঞ্জ সদর "},
  {"district_id": 56, "name": "Kishorganj/কিশোরগঞ্জ "},
  {"district_id": 71, "name": "Koloni Bazar/কলোনি বাজার "},
  {"district_id": 71, "name": "Koshaibari/কোশাইবাড়ি "},
  {"district_id": 51, "name": "Kotalipara/কোটালীপাড়া "},
  {"district_id": 29, "name": "Kotchandpur/কোটচাঁদপুর "},
  {"district_id": 27, "name": "Koyra/কয়রা "},
  {"district_id": 37, "name": "Kulaura/কুলাউড়া "},
  {"district_id": 45, "name": "Kuliarchar/কুলিয়ারচর "},
  {"district_id": 25, "name": "Kumarkhali/কুমারখালী "},
  {"district_id": 71, "name": "Kunipara/কুনিপাড়া "},
  {"district_id": 60, "name": "Kurigram Sadar/কুড়িগ্রাম সদর "},
  {"district_id": 71, "name": "Kuril/কুড়িল "},
  {"district_id": 71, "name": "Kuril bus stop/কুড়িল বাস স্টপ "},
  {"district_id": 71, "name": "Kurmitola/কুর্মিটোলা "},
  {"district_id": 25, "name": "Kushtia Sadar/কুষ্টিয়া সদর "},
  {"district_id": 9, "name": "Kutubdia/কুতুবদিয়া "},
  {
    "district_id": 72,
    "name": "Kuwait friendship hospital/কুয়েত ফ্রেন্ডশিপ হাসপাতাল "
  },
  {"district_id": 38, "name": "Lakhai/লাখাই "},
  {"district_id": 1, "name": "Laksam/লাকসাম "},
  {"district_id": 7, "name": "Lakshmipur Sadar/লক্ষ্মীপুর সদর "},
  {"district_id": 72, "name": "Lal Mohan Poddar Lane/লাল মহান পোদ্দার লেন "},
  {"district_id": 72, "name": "Lalbagh/লালবাগ "},
  {"district_id": 1, "name": "Lalmai/লালমাই "},
  {"district_id": 72, "name": "Lalmatia/লালমাটিয়া "},
  {"district_id": 34, "name": "Lalmohan/লালমোহন "},
  {"district_id": 72, "name": "Lalmohan Shah Street/লালমোহন শাহ স্ট্রেট "},
  {"district_id": 55, "name": "Lalmonirhat Sadar/লালমনিরহাট সদর "},
  {"district_id": 16, "name": "Lalpur/লালপুর "},
  {"district_id": 11, "name": "Lama/লামা "},
  {"district_id": 4, "name": "Langadu/লংগাদু "},
  {"district_id": 72, "name": "Large katra/লার্জ কাটরা "},
  {"district_id": 10, "name": "Laxmichhari/লাক্ষিছরি "},
  {"district_id": 8, "name": "Lohagara/লোহাগাড়া "},
  {"district_id": 23, "name": "Lohagara/লোহাগাড়া "},
  {"district_id": 48, "name": "Louhaganj/লৌহাগঞ্জ "},
  {"district_id": 64, "name": "Madan/মাদান "},
  {"district_id": 72, "name": "Madan Mohan Basak Road/মাদান মহান বসাক রোড "},
  {"district_id": 72, "name": "Madanshah Lane/মাদানশাহ্ লেন "},
  {"district_id": 63, "name": "Madarganj/মাদারগঞ্জ "},
  {"district_id": 50, "name": "Madaripur Sadar/মাদারীপুর সদর "},
  {"district_id": 72, "name": "Madartek/মাদারটেক "},
  {"district_id": 38, "name": "Madhabpur/মাধাবপুর "},
  {"district_id": 52, "name": "Madhukhali/মধুখালী "},
  {"district_id": 44, "name": "Madhupur/মধুপুর "},
  {"district_id": 26, "name": "Magura Sadar/মাগুরা সদর "},
  {"district_id": 72, "name": "Malakartola Lane/মালাকারতোলা লেন "},
  {"district_id": 72, "name": "Malibag/মালিবাগ "},
  {"district_id": 71, "name": "Malibag bus stand/মালিবাগ বাস স্ট্যান্ড "},
  {"district_id": 71, "name": "Malibag railgate/মালিবাগ রেলঘুন্টি "},
  {"district_id": 72, "name": "Malibagh Bazar Road/মালিবাগ বাজার রোড "},
  {"district_id": 72, "name": "Malitola lane/মালিতলা লেন "},
  {"district_id": 19, "name": "Manda/মান্দা "},
  {"district_id": 72, "name": "Manik Nagar/মানিক নগর "},
  {
    "district_id": 72,
    "name": "Manik Nagar Miyazan Lane/মানিক নগর মিয়াজান লেন "
  },
  {"district_id": 10, "name": "Manikchari/মানিকছড়ি "},
  {"district_id": 71, "name": "Manikdi/মানিকদী "},
  {"district_id": 46, "name": "Manikganj Sadar/মানিকগঞ্জ সদর "},
  {"district_id": 72, "name": "Maniknagar/মানিক নগর "},
  {"district_id": 20, "name": "Manirampur/মনিরামপুর "},
  {"district_id": 72, "name": "Maradia/মেরাদিয়া "},
  {"district_id": 71, "name": "Masranga Television/মাশরাঙা টেলিভিশন "},
  {"district_id": 32, "name": "Mathbaria/মঠবাড়িয়া "},
  {"district_id": 71, "name": "Matikata/মাটিকাটা "},
  {"district_id": 10, "name": "Matiranga/মাটিরাঙ্গা "},
  {"district_id": 72, "name": "Matitola lane/মতিতলা লেন "},
  {"district_id": 6, "name": "Matlab North/উত্তর মতলব  "},
  {"district_id": 6, "name": "Matlab South/দক্ষিন মতলব"},
  {"district_id": 72, "name": "Matuail/মাতুয়াইল "},
  {"district_id": 72, "name": "Mayakanon/মায়াকানন "},
  {"district_id": 1, "name": "Meghna/মেঘনা "},
  {"district_id": 33, "name": "Mehendiganj/মেহেনদীগঞ্জ "},
  {"district_id": 22, "name": "Meherpur Sadar/মেহেরপুর সদর "},
  {"district_id": 63, "name": "Melandah/মেলান্দহ "},
  {"district_id": 71, "name": "Meradia/মেরাদিয়া "},
  {"district_id": 71, "name": "Meradia Graveyeard/মেরাদিস গ্রাভেইয়ার্ড "},
  {"district_id": 71, "name": "Meradia kacha bazar/মেরাদিয়া কাচা বাজার "},
  {"district_id": 71, "name": "Merul/মেরুল "},
  {"district_id": 72, "name": "Methorpotty/মেথরপটটি "},
  {"district_id": 72, "name": "Middle Bashabo/মধ্য বাসাবো "},
  {"district_id": 71, "name": "Middle Meradia/মধ্য মেরাদিয়া "},
  {"district_id": 71, "name": "Middle badda/মধ্য বাড্ডা "},
  {"district_id": 72, "name": "Mill Barracks/মিলল ব্যারাকস্ "},
  {"district_id": 72, "name": "Mintu Road/মিন্টু রোড "},
  {"district_id": 72, "name": "Mir Hazaribagh/মীর হাজারিবাঘ "},
  {"district_id": 71, "name": "Mirbag/মীরবাঘ"},
  {"district_id": 25, "name": "Mirpur/মিরপুর "},
  {"district_id": 71, "name": "Mirpur 1/মিরপুর১"},
  {"district_id": 71, "name": "Mirpur 10/মিরপুর ১০"},
  {"district_id": 71, "name": "Mirpur 11 - 13/মিরপুর ১১-১৩"},
  {"district_id": 71, "name": "Mirpur 60 Feet/মিরপুর ৬০ ফিট "},
  {
    "district_id": 71,
    "name": "Mirpur Botanical Garden/মিরপুর বোটানিক্যাল গার্ডেন "
  },
  {"district_id": 71, "name": "Mirpur Cantonment/মিরপুর ক্যান্টনমেন্ট "},
  {"district_id": 71, "name": "Mirpur Ceramic/মিরপুর সিরামিক্ "},
  {"district_id": 71, "name": "Mirpur Colony/মিরপুর কলোনী "},
  {"district_id": 71, "name": "Mirpur DOHS/মিরপুর দশ "},
  {"district_id": 71, "name": "Mirpur Darus Salam/মিরপুর দ্বারুসসালাম "},
  {
    "district_id": 71,
    "name": "Mirpur Govt Housing Estate/মিরপুর গোবৎ হাউসিং স্ট্রেট "
  },
  {"district_id": 71, "name": "Mirpur Kazipara/মিরপুর কাজিপাড়া "},
  {"district_id": 71, "name": "Mirpur Rupnagar/মিরপুর রূপনগর "},
  {"district_id": 71, "name": "Mirpur Section 1/মিরপুর সেকশন ১"},
  {"district_id": 71, "name": "Mirpur Section 11/মিরপুর সেকশন ১১"},
  {"district_id": 71, "name": "Mirpur Section 12/ মিরপুর সেকশন ১২"},
  {"district_id": 71, "name": "Mirpur Section 13/মিরপুর সেকশন ১৩"},
  {"district_id": 71, "name": "Mirpur Section 14/মিরপুর সেকশন ১৪"},
  {"district_id": 71, "name": "Mirpur Section 15/মিরপুর সেকশন ১৫"},
  {"district_id": 71, "name": "Mirpur Section 16/মিরপুর সেকশন ১৬"},
  {"district_id": 71, "name": "Mirpur Section 2/মিরপুর সেকশন ২"},
  {"district_id": 71, "name": "Mirpur Section 3/মিরপুর সেকশন ৩"},
  {"district_id": 71, "name": "Mirpur Section 4/ মিরপুর সেকশন ৪"},
  {"district_id": 71, "name": "Mirpur Section 5/মিরপুর সেকশন ৫"},
  {"district_id": 71, "name": "Mirpur Section 6/Mirpur মিরপুর সেকশন ৬"},
  {"district_id": 71, "name": "Mirpur Section 7/মিরপুর সেকশন ৭"},
  {"district_id": 71, "name": "Mirpur Section 8/মিরপুর সেকশন ৮"},
  {"district_id": 71, "name": "Mirpur Section 9/মিরপুর সেকশন ৯"},
  {"district_id": 71, "name": "Mirpur Shewrapara/মিরপুর শেওড়াপাড়া "},
  {"district_id": 71, "name": "Mirpur Taltola/মিরপুর তালতলা "},
  {"district_id": 71, "name": "Mirpur Zoo/মিরপুর জোও "},
  {"district_id": 8, "name": "Mirsharai/মিরসরাই "},
  {"district_id": 31, "name": "Mirzaganj/মির্জাগঞ্জ "},
  {"district_id": 44, "name": "Mirzapur/মির্জাপুর "},
  {"district_id": 72, "name": "Mitali road/মিতালি রোড "},
  {"district_id": 72, "name": "Mitfort Road/মিটফোর্ট রোড "},
  {"district_id": 45, "name": "Mithamoin/মিঠামইন "},
  {"district_id": 59, "name": "Mithapukur/মিঠাপুকুর "},
  {"district_id": 71, "name": "Modhubag/মধুবাগ "},
  {
    "district_id": 72,
    "name": "Mogbazar Circuit House Road/ মগবাজার সার্কিট হাউস রোড "
  },
  {"district_id": 72, "name": "Moghbazar/মগবাজার "},
  {"district_id": 72, "name": "Moghbazar TNT colony/মগবাজার টি,এন,টি, কলোনী "},
  {"district_id": 19, "name": "Mohadevpur/মহাদেবপুর "},
  {"district_id": 71, "name": "Mohak/মহাক "},
  {"district_id": 71, "name": "Mohakhali Bus Stand/মহাখালী বাস স্ট্যান্ড "},
  {"district_id": 71, "name": "Mohakhali DOHS/মহাখালী দশ "},
  {
    "district_id": 71,
    "name":
        "Mohakhali Inter District Bus Terminal/মহাখালী ইন্টার ডিস্ট্রিক্ট বাস টার্মিনাল "
  },
  {"district_id": 71, "name": "Mohakhali Kachabazar/মহাখালী কাঁচাবাজার "},
  {
    "district_id": 71,
    "name": "Mohakhali TB Gate Jame Mosjid/মহাখালী টি,বি, গেট জামে মসজিদ "
  },
  {"district_id": 71, "name": "Mohakhali koraill Basti/মহাখালী কড়াইল বসতি"},
  {"district_id": 10, "name": "Mohalchari/মহালচড়ি "},
  {
    "district_id": 71,
    "name": "Mohammadia Housing Limited/মোহাম্মদীয়া হাউসিং লিমিটেড "
  },
  {"district_id": 26, "name": "Mohammadpur/মোহাম্ম্মদপুর "},
  {
    "district_id": 71,
    "name": "Mohammadpur Chandmiya Housing/মোহাম্মদপুর চাঁদমিয়া হাউসিং "
  },
  {
    "district_id": 71,
    "name":
        "Mohammadpur Mohammadia Housing Society/মোহাম্মদপুর মোহাম্মদীয়া হাউসিং সোসাইটি  "
  },
  {
    "district_id": 71,
    "name":
        "Mohammadpur Mohammadia Non Housing Area/মোহাম্মদপুর মোহাম্মদীয়া নন হাউসিং এরিয়া "
  },
  {
    "district_id": 71,
    "name":
        "Mohammadpur P C Culture Society/মোহাম্মদপুর পি, সি, কালচার সোসাইটি "
  },
  {
    "district_id": 71,
    "name": "Mohammadpur Residential Area/মোহাম্মদপুর রেসিডেন্সিয়াল এরিয়া "
  },
  {"district_id": 9, "name": "Moheshkhali/মহেশখালী "},
  {"district_id": 29, "name": "Moheshpur/মহেশপুর "},
  {"district_id": 72, "name": "Mohini Mohandas Lane/মোহিনী মোহনদাস লেন "},
  {"district_id": 64, "name": "Mohongonj/মোহনগঞ্জ "},
  {"district_id": 15, "name": "Mohonpur/মোহনপুর "},
  {"district_id": 72, "name": "Mokim Katara/মকিম কাটার "},
  {"district_id": 28, "name": "Mollahat/মোল্লাহাট "},
  {"district_id": 72, "name": "Momenbagh/মোমেনবাগ "},
  {"district_id": 28, "name": "Mongla/মংলা"},
  {"district_id": 71, "name": "Monipur/মনিপুর "},
  {"district_id": 71, "name": "Monipuri Para/মনিপুরী পাড়া "},
  {"district_id": 40, "name": "Monohardi/মনোহরদী "},
  {"district_id": 1, "name": "Monohargonj/মনোহরগঞ্জ "},
  {"district_id": 34, "name": "Monpura/মনপুরা "},
  {"district_id": 28, "name": "Morrelganj/মোড়েলগঞ্জ "},
  {"district_id": 72, "name": "Motijheel/মতিঝিল "},
  {"district_id": 72, "name": "Motijheel Colony/মতিঝিল কলোনী "},
  {
    "district_id": 72,
    "name": "Motijheel Commercial Area/মতিঝিল কমার্শিয়াল এরিয়া "
  },
  {"district_id": 71, "name": "Mouchak/মৌচাক "},
  {"district_id": 37, "name": "Moulvibazar Sadar/মৌলভীবাজার সদর "},
  {"district_id": 72, "name": "Mugda/মুগদা "},
  {"district_id": 72, "name": "Mugdapara/মুগদা পাড়া "},
  {"district_id": 22, "name": "Mujibnagar/মুজিবনগর "},
  {"district_id": 51, "name": "Muksudpur/মুকছেদপুর "},
  {"district_id": 62, "name": "Muktagacha/মুক্তাগাছা "},
  {"district_id": 33, "name": "Muladi/মুলাদী "},
  {
    "district_id": 72,
    "name": "Municipal Staff Quarter/ মিউনিসিপাল স্টাফ কোয়ার্টার"
  },
  {"district_id": 72, "name": "Munir Hossain Lane/মুনির হোসাইন লেন "},
  {"district_id": 48, "name": "Munshiganj Sadar/মুন্সীগঞ্জ সদর "},
  {"district_id": 1, "name": "Muradnagar/মুরাদনগর "},
  {"district_id": 72, "name": "Muradpur/মৌরাদপুর "},
  {"district_id": 62, "name": "Mymensingh Sadar/ময়মনসিংহ্ সদর "},
  {"district_id": 72, "name": "Mymensingh lane/ ময়মনসিংহ্ লেন "},
  {"district_id": 72, "name": "Nabalka Mia lane/নাবালিকা মিয়া লেন "},
  {"district_id": 38, "name": "Nabiganj/নবীগঞ্জ "},
  {"district_id": 3, "name": "Nabinagar/নবীনগর "},
  {"district_id": 71, "name": "Nabisco Bus Stand/নাবিস্কো বাস স্ট্যান্ড "},
  {"district_id": 18, "name": "Nachol/নাচোল "},
  {"district_id": 71, "name": "Nadda/নাড্ডা "},
  {"district_id": 52, "name": "Nagarkanda/নগরকান্দা "},
  {"district_id": 44, "name": "Nagarpur/নাগরপুর "},
  {"district_id": 60, "name": "Nageshwari/নাগেশ্বরী "},
  {"district_id": 11, "name": "Naikhongchhari/নাইক্ষ্যংছড়ি "},
  {"district_id": 71, "name": "Nakhalpara/নাখালপাড়া "},
  {"district_id": 30, "name": "Nalchity/নলছিটি "},
  {"district_id": 16, "name": "Naldanga/নলডাঙ্গা "},
  {"district_id": 61, "name": "Nalitabari/নালিতাবাড়ী "},
  {"district_id": 71, "name": "Nama Para/নাম পাড়া "},
  {"district_id": 62, "name": "Nandail/নান্দাইল "},
  {"district_id": 1, "name": "Nangalkot/নাঙ্গলকোট "},
  {"district_id": 4, "name": "Naniarchar/নানিয়ারচর "},
  {"district_id": 19, "name": "Naogaon Sadar/নওগাঁ সদর "},
  {"district_id": 23, "name": "Narail Sadar/নড়াইল সদর"},
  {"district_id": 43, "name": "Narayanganj Sadar/নারায়ণগঞ্জ সদর "},
  {"district_id": 42, "name": "Naria/নাড়িয়া "},
  {"district_id": 72, "name": "Narinda Lane/নারিন্দা লেন "},
  {"district_id": 72, "name": "Narinda Road/নারিন্দা রোড "},
  {"district_id": 40, "name": "Narsingdi Sadar/নরসিংদী সদর "},
  {"district_id": 71, "name": "Nasir er tek/নাসির এর টেক "},
  {"district_id": 3, "name": "Nasirnagar/নাসিরনগর "},
  {
    "district_id": 72,
    "name": "National Museum Quarter/ন্যাশনাল মিউজিয়াম কোয়ার্টার "
  },
  {"district_id": 16, "name": "Natore Sadar/নাটোর সদর "},
  {
    "district_id": 72,
    "name": "Naveen Chandra Gombasi Road/নাভীন চান্দ্রা গামবাসী রোড "
  },
  {"district_id": 72, "name": "Nawab Deori/নবাব দেউড়ি "},
  {"district_id": 72, "name": "Nawab Katara/নবাব কাটার "},
  {"district_id": 72, "name": "Nawab Street/নবাব স্ট্রেট "},
  {"district_id": 47, "name": "Nawabganj/নবাবগঞ্জ "},
  {"district_id": 54, "name": "Nawabganj/নবাবগঞ্জ "},
  {"district_id": 72, "name": "Nawabganj/নবাবগঞ্জ "},
  {"district_id": 72, "name": "Nayapalton/নয়াপল্টন "},
  {"district_id": 72, "name": "Nazira Bazar Lane/নাজিরা বাজার লেন "},
  {"district_id": 32, "name": "Nazirpur/নাজিরপুর "},
  {"district_id": 72, "name": "Nazrul Islam Hall/নজরুল ইসলাম হল "},
  {"district_id": 72, "name": "Neki Deori/নাকি ডায়রি "},
  {"district_id": 32, "name": "Nesarabad/নেসারাবাদ "},
  {"district_id": 64, "name": "Netrokona Sadar/নেত্রকোনা সদর "},
  {"district_id": 72, "name": "New Eskaton Road/নিউ ইস্কাটন রোড "},
  {"district_id": 72, "name": "New Jurain Alam Bagh/নিউ জুরাইন এলাম বাঘ "},
  {"district_id": 72, "name": "New market/নিউ মার্কেট "},
  {"district_id": 19, "name": "Niamatpur/নিয়ামতপুর "},
  {"district_id": 71, "name": "Niketon/নিকেতন "},
  {"district_id": 71, "name": "Niketon Bazar gate/নিকেতন বাজার গেট "},
  {"district_id": 45, "name": "Nikli/নিকলী "},
  {"district_id": 71, "name": "Nikunja 1/নিকুঞ্জ ১"},
  {"district_id": 71, "name": "Nikunja 2/নিকুঞ্জ ২"},
  {"district_id": 72, "name": "Nilkhet Babupara/নিকুঞ্জ বাবুপাড়া "},
  {"district_id": 56, "name": "Nilphamari Sadar/নীলফামারী সদর "},
  {"district_id": 5, "name": "Noakhali Sadar/নোয়াখালী সদর "},
  {"district_id": 61, "name": "Nokla/নকলা "},
  {"district_id": 14, "name": "Nondigram/নন্দীগ্রাম "},
  {"district_id": 71, "name": "Nondipara Bazar/নন্দীপাড়া বাজার "},
  {"district_id": 72, "name": "Noor box Lane/নূর বাক্স লেন "},
  {"district_id": 72, "name": "North Bashabo/উত্তর বাসাবো "},
  {"district_id": 72, "name": "North Circular Road/উত্তর সার্কুলার রোড "},
  {"district_id": 72, "name": "North Jatrabari/উত্তর যাত্রাবাড়ী "},
  {
    "district_id": 72,
    "name": "North Mugdapara Deputy Colony/উত্তর মুগদাপাড়া ডেপুটি কলোনী "
  },
  {"district_id": 72, "name": "North Rajarbagh/উত্তর রাজারবাগ "},
  {"district_id": 72, "name": "North Road /উত্তর রোড "},
  {"district_id": 72, "name": "NorthEast Bashabo/উত্তর বাসাবো "},
  {"district_id": 72, "name": "NorthWest Jatrabari/উত্তর যাত্রাবাড়ী "},
  {"district_id": 71, "name": "Notunbag/নতুনবাগ "},
  {"district_id": 71, "name": "Notunbazar Bus Stand/নতুনবাজার বাস স্ট্যান্ড "},
  {"district_id": 71, "name": "Noyatola/নয়াতলা "},
  {"district_id": 71, "name": "Nurer Chala/নূরের চালা "},
  {"district_id": 72, "name": "Old Railway Station/পুরাতন রেলওয়ে স্টেশন "},
  {"district_id": 36, "name": "Osmaninagar/ওসমানিনগর "},
  {"district_id": 72, "name": "Outer Circular Road/আউটার সারকুলার রোড "},
  {"district_id": 72, "name": "PG Hospital/পি,জি, হাসপাতাল "},
  {"district_id": 15, "name": "Paba/পবা "},
  {"district_id": 13, "name": "Pabna Sadar/পাবনা সদর "},
  {"district_id": 72, "name": "Padma Nidhi Lane/পদ্মা নিধি লেন "},
  {"district_id": 72, "name": "Padmolochan Roy Lane/পদ্মলোচন রায় লেন "},
  {"district_id": 27, "name": "Paikgasa/পাইকগাছা "},
  {"district_id": 71, "name": "Paikpara/পাইকপাড়া "},
  {"district_id": 45, "name": "Pakundia/পাকুন্দিয়া "},
  {"district_id": 72, "name": "Palamganj/পালামগঞ্জ "},
  {"district_id": 40, "name": "Palash/পলাশ "},
  {"district_id": 57, "name": "Palashbari/পলাশবাড়ী "},
  {"district_id": 72, "name": "Pallabi/পল্লবী "},
  {"district_id": 72, "name": "Palton/পল্টন "},
  {"district_id": 53, "name": "Panchagarh Sadar/পঞ্চগড় সদর "},
  {"district_id": 10, "name": "Panchari/পানছড়ি "},
  {"district_id": 17, "name": "Panchbibi/পঞ্চবুবি "},
  {"district_id": 49, "name": "Pangsa/পাংশা "},
  {"district_id": 54, "name": "Parbatipur/পার্বতীপুর "},
  {"district_id": 72, "name": "Paribagh Shah Sahib Road/পরীবাগঃ শাহ সহীব রোড "},
  {"district_id": 2, "name": "Parshuram/পরশুরাম "},
  {"district_id": 71, "name": "Paschim Rampura/পশ্চিম রামপুরা "},
  {"district_id": 55, "name": "Patgram/পাটগ্রাম "},
  {"district_id": 35, "name": "Pathorghata/পাথরঘাটা "},
  {"district_id": 8, "name": "Patiya/পাতিয়া "},
  {"district_id": 72, "name": "Patlakhan Lane/পাতলাখান লেন "},
  {"district_id": 19, "name": "Patnitala/পত্নীতলা "},
  {"district_id": 31, "name": "Patuakhali Sadar/পটুয়াখালী "},
  {"district_id": 72, "name": "Patuatuli Lane/পাটুয়াটুলী লেন "},
  {"district_id": 9, "name": "Pekua/পেকুয়া "},
  {"district_id": 60, "name": "Phulbari/ফুলবাড়ী "},
  {"district_id": 57, "name": "Phulchari/ফুলছড়ি "},
  {"district_id": 62, "name": "Phulpur/ফুলপুর "},
  {"district_id": 71, "name": "Pink City/পিঙ্ক সিটি "},
  {"district_id": 71, "name": "Pirerbagh/পীরেরবাগ "},
  {"district_id": 59, "name": "Pirgacha/পীরগাছা "},
  {"district_id": 58, "name": "Pirganj/পীরগঞ্জ "},
  {"district_id": 59, "name": "Pirgonj/পীরগঞ্জ "},
  {"district_id": 32, "name": "Pirojpur Sadar/পিরোজপুর সদর "},
  {"district_id": 72, "name": "Poet Jasim Uddin Hall/কবিরাজ  জসিম উদ্দিন হল "},
  {"district_id": 72, "name": "Police Hospital/পুলিশ হাসপাতাল "},
  {"district_id": 72, "name": "Police Line/পুলিশ লাইন "},
  {"district_id": 71, "name": "Police Plaza/পুলিশ প্লাজা "},
  {"district_id": 19, "name": "Porsha/পোরশা "},
  {"district_id": 72, "name": "Postagola/পোস্তগোলা "},
  {"district_id": 72, "name": "Postal Colony/পোস্টাল কলোনী "},
  {"district_id": 71, "name": "Prembagan/প্রেমবাগান "},
  {"district_id": 72, "name": "Puran Mogul/পুরান মোগল "},
  {"district_id": 72, "name": "Purana Paltan GPO/পুরাণ পাল্টান জিপ "},
  {"district_id": 72, "name": "Purana Paltan Line/পুরাণ পাল্টান লাইন "},
  {"district_id": 64, "name": "Purbadhala/পূর্বধলা "},
  {"district_id": 15, "name": "Puthia/পুঠিয়া "},
  {"district_id": 72, "name": "R K Mission Road/আর কে লাগে ল মিশন রোড "},
  {"district_id": 72, "name": "Rai Ishrat Chandta/রাই ইশরাত চাঁদটা   "},
  {"district_id": 12, "name": "Raigonj/রায়গঞ্জ "},
  {"district_id": 72, "name": "Railway Hospital area/রেলওয়ে হাসপাতাল এরিয়া "},
  {"district_id": 7, "name": "Raipur/রায়পুর "},
  {"district_id": 40, "name": "Raipura/রায়পুরা "},
  {"district_id": 72, "name": "Rajabagh Police Line/রাজাবাগঃ পুলিশ লাইন "},
  {"district_id": 72, "name": "Rajani Bose Lane/রাজনী বিষয়ে লেন "},
  {"district_id": 30, "name": "Rajapur/রাজপুর "},
  {"district_id": 71, "name": "Rajarbag Police Line/রাজারবাগ পুলিশ লাইন "},
  {"district_id": 60, "name": "Rajarhat/রাজারহাট "},
  {"district_id": 4, "name": "Rajasthali/রাজস্থলী "},
  {"district_id": 49, "name": "Rajbari Sadar/রাজবাড়ী সদর "},
  {"district_id": 37, "name": "Rajnagar/রাজনগর "},
  {"district_id": 72, "name": "Rajni Chowdhury Road/রাজনী চৌধুরী "},
  {"district_id": 50, "name": "Rajoir/রাজৈর "},
  {
    "district_id": 72,
    "name": "Rakhal chandra bashak lane/রাখাল চান্দ্রা বসাক লেন "
  },
  {"district_id": 7, "name": "Ramganj/রামগঞ্জ "},
  {"district_id": 10, "name": "Ramgarh/রামগড় "},
  {"district_id": 7, "name": "Ramgati/রামগতি "},
  {"district_id": 72, "name": "Ramna/রমনা "},
  {"district_id": 28, "name": "Rampal/রামপাল "},
  {"district_id": 72, "name": "Rampura/রামপুরা "},
  {"district_id": 71, "name": "Rampura Bazar/রামপুরা বাজার "},
  {"district_id": 71, "name": "Rampura Bus Stand/রামপুরা বাস স্ট্যান্ড "},
  {"district_id": 9, "name": "Ramu/রামু "},
  {"district_id": 31, "name": "Rangabali/রাঙ্গাবালী "},
  {"district_id": 4, "name": "Rangamati Sadar/রাঙামাটি "},
  {"district_id": 59, "name": "Rangpur Sadar/রংপুর সদর "},
  {"district_id": 8, "name": "Rangunia/রাঙ্গুনিয়া "},
  {"district_id": 19, "name": "Raninagar/রাণীনগর "},
  {"district_id": 58, "name": "Ranisankail/রাণীশংকৈল "},
  {"district_id": 8, "name": "Raozan/রাউজান "},
  {"district_id": 71, "name": "Rasulbagh/রাসূলদাঘ"},
  {"district_id": 72, "name": "Rishikosh Das Road/রিষাকোষ দাস রোড "},
  {"district_id": 72, "name": "Rokaya Hall/রোকেয়া হল "},
  {"district_id": 11, "name": "Rowangchhari/রিয়াওয়াংছড়ি "},
  {"district_id": 60, "name": "Rowmari/রৌমারী "},
  {"district_id": 72, "name": "Roy Bahadur Road/রায় বাহাদুর রোড "},
  {"district_id": 72, "name": "Rubber Bose Street/রবার বসে  স্ট্রেট "},
  {"district_id": 72, "name": "Rui Hatra/রুই হাত্রা "},
  {"district_id": 11, "name": "Ruma/রুমা "},
  {"district_id": 72, "name": "Rupa das lal lane/রুপা দাস লাল লেন "},
  {"district_id": 72, "name": "Rupchan Lane/রূপচাঁ লেন "},
  {"district_id": 43, "name": "Rupganj/রূপগঞ্জ "},
  {"district_id": 27, "name": "Rupsha/রূপসা "},
  {"district_id": 72, "name": "Sabujbagh/সবুজবাগ "},
  {"district_id": 52, "name": "Sadarpur/সদরপুর "},
  {"district_id": 1, "name": "Sadarsouth/সাদারসুৎ "},
  {"district_id": 57, "name": "Sadullapur/সাদুল্লাপুর "},
  {"district_id": 57, "name": "Saghata/সাঘাটা "},
  {"district_id": 72, "name": "Saidabad/সায়দাবাদ"},
  {"district_id": 44, "name": "Sakhipur/সখিপুর "},
  {"district_id": 72, "name": "Salimullah Hall/সলিমুল্লাহ হল "},
  {"district_id": 52, "name": "Saltha/সালথা "},
  {"district_id": 72, "name": "Samaswada lane/সমস্বাদ লেন "},
  {"district_id": 8, "name": "Sandwip/সন্দ্বীপ "},
  {"district_id": 13, "name": "Santhia/সাঁথিয়া "},
  {"district_id": 19, "name": "Sapahar/সাপাহার "},
  {"district_id": 3, "name": "Sarail/সরাইল "},
  {"district_id": 28, "name": "Sarankhola/শরণখোলা "},
  {"district_id": 63, "name": "Sarishabari/সরিষাবাড়ী "},
  {"district_id": 72, "name": "Sarulia/সারুলিয়া "},
  {"district_id": 72, "name": "Satish Sarkar Road/সতীশ সরকার রোড "},
  {"district_id": 8, "name": "Satkania/সাতকানিয়া "},
  {"district_id": 21, "name": "Satkhira Sadar/সাতক্ষীরা সদর "},
  {"district_id": 72, "name": "Satmasjid Road/সাতমসজিদ রোড "},
  {"district_id": 71, "name": "Satrasta/সাতরাস্তা "},
  {"district_id": 46, "name": "Saturia/সাটুরিয়া "},
  {"district_id": 47, "name": "Savar/সাভার "},
  {"district_id": 72, "name": "Sayed hasan Ali Lane/সায়ৈদ হাসান আলী লেন "},
  {"district_id": 72, "name": "Secretariat Road/সেক্রেটারিয়েট রোড "},
  {"district_id": 72, "name": "Segun Bagicha /সেগুন বাগিচা "},
  {"district_id": 5, "name": "Senbug/সেনবাগ "},
  {"district_id": 72, "name": "Shah Shaheb Lane/ শাহ সাহেব লেন "},
  {"district_id": 72, "name": "Shahbagh/শাহবাগ "},
  {"district_id": 72, "name": "Shaheed Memorial Hall/শহীদ মেমোরিয়াল হল "},
  {"district_id": 72, "name": "Shahidbagh/শহীদবাঘ "},
  {"district_id": 72, "name": "Shahidullah Hall/শহীদুল্লাহ হল "},
  {"district_id": 71, "name": "Shahinbag/শাহিনবাগ "},
  {"district_id": 12, "name": "Shahjadpur/শাহজাদপুর "},
  {
    "district_id": 71,
    "name": "Shahjahadpur Bus Stand/শাহ্জাহাপুর বাস স্ট্যান্ড "
  },
  {"district_id": 72, "name": "Shahjahanpur/শাহজাহানপুর "},
  {
    "district_id": 72,
    "name": "Shahjahanpur Railway Colony/শাহজাহানপুর রেলওয়ে কলোনী "
  },
  {"district_id": 71, "name": "Shahjahdpur/শাহ্জাহাদপুর "},
  {"district_id": 6, "name": "Shahrasti/শাহ্রাস্তি "},
  {"district_id": 29, "name": "Shailkupa/শৈলকুপা "},
  {"district_id": 14, "name": "Shajahanpur/শাজাহানপুর "},
  {"district_id": 72, "name": "Shakhari Bazar Road/শাখারি বাজার রোড "},
  {"district_id": 72, "name": "Shakhari Nagar Lane/শাখারি নগর লেন "},
  {"district_id": 26, "name": "Shalikha/শালিখা "},
  {"district_id": 39, "name": "Shalla/শাল্লা "},
  {"district_id": 72, "name": "Shamsun Nahar Hall/শামসুন নাহার হল "},
  {"district_id": 72, "name": "Shantibagh/শান্তিবাগ "},
  {"district_id": 72, "name": "Shantinagar/শান্তিনগর "},
  {
    "district_id": 72,
    "name": "Shantinagar Market Area/শান্তিগর মার্কেট এরিয়া "
  },
  {"district_id": 71, "name": "Shantiniketon/শান্তিনিকেতন "},
  {"district_id": 71, "name": "Shantipur/শান্তিপুর "},
  {
    "district_id": 72,
    "name": "Sharat chandra chakraborty lane/শারৎ চান্দ্রা চক্রবর্তী লেন "
  },
  {"district_id": 72, "name": "Sharatgupta Road/শারাতগুপ্ত রোড "},
  {"district_id": 14, "name": "Shariakandi/সারিয়াকান্দি "},
  {"district_id": 42, "name": "Shariatpur Sadar/শরীয়তপুর সদর "},
  {"district_id": 71, "name": "Sharnalata/সারনালাটা "},
  {"district_id": 20, "name": "Sharsha/শার্শা "},
  {
    "district_id": 72,
    "name": "Shashibhushan Chaterjee Lane/শশীভূষণ চ্যাটার্জী লেন "
  },
  {
    "district_id": 72,
    "name": "Sheikh Majibur Rahman Hall/শেখ মজিবুর রহমান হল "
  },
  {"district_id": 71, "name": "Shena Maloncha/সেনা মালঞ্চ "},
  {"district_id": 71, "name": "Shenpara Parbata/সেনপাড়া পর্বটা "},
  {"district_id": 72, "name": "Sher e Bangla Road/শের এ বাংলা রোড "},
  {"district_id": 71, "name": "Sher-e-Bangla Nagar/শের -এ বাংলা নাগার "},
  {"district_id": 72, "name": "Sherabangla Hall/শের-এ-বাংলা হল "},
  {"district_id": 14, "name": "Sherpur/শেরপুর "},
  {"district_id": 61, "name": "Sherpur Sadar/শেরপুর সদর "},
  {"district_id": 71, "name": "Shewrapara/শেওড়াপাড়া "},
  {"district_id": 46, "name": "Shibaloy/শিবালয় "},
  {"district_id": 50, "name": "Shibchar/শিবচর "},
  {"district_id": 14, "name": "Shibganj/শিবগঞ্জ "},
  {"district_id": 18, "name": "Shibganj/শিবগঞ্জ "},
  {"district_id": 40, "name": "Shibpur/শিবপুর "},
  {"district_id": 71, "name": "Shiddheshwari/সিদ্ধেশ্বরী "},
  {"district_id": 71, "name": "Shipahibag/সিপাহীবাগ "},
  {"district_id": 71, "name": "Shonirakhra/শনিরআখড়া "},
  {"district_id": 72, "name": "Shukrabad/শুক্রাবাদ "},
  {"district_id": 72, "name": "Shurwardi Hall/সরোয়ার্দী হল "},
  {"district_id": 21, "name": "Shyamnagar/শ্যামনগর "},
  {"district_id": 71, "name": "Shyamoli/শ্যামলী "},
  {"district_id": 72, "name": "Siddheshwari Road/সিদ্ধেশ্বরী রোড "},
  {"district_id": 72, "name": "Siddique bazar/সিদ্দিক বাজার "},
  {"district_id": 72, "name": "Siddique lane/সিদ্দিক লেন "},
  {"district_id": 72, "name": "Sikkatuli lane/সাক্ষিতলি লেন "},
  {"district_id": 72, "name": "Simson Road/সিমসোং রোড "},
  {"district_id": 46, "name": "Singiar/সিংগিয়ার "},
  {"district_id": 16, "name": "Singra/সিংড়া "},
  {
    "district_id": 71,
    "name": "Sipahi bag tampoo stand/সিপাহী ব্যাগ টেম্পো স্ট্যান্ড "
  },
  {"district_id": 72, "name": "Sir AF Rahman hall/স্যার এ,এফ, রহমান হল "},
  {"district_id": 48, "name": "Sirajdikhan/সিরাজদিখান "},
  {"district_id": 12, "name": "Sirajganj Sadar/সিরাজগঞ্জ সদর "},
  {"district_id": 8, "name": "Sitakunda/সীতাকুণ্ড "},
  {"district_id": 72, "name": "Sobhanbagh/সোবহানবাগ "},
  {"district_id": 71, "name": "Solmaid/সোলমাইড "},
  {"district_id": 71, "name": "Sona katra/সোনা কাটরা "},
  {"district_id": 2, "name": "Sonagazi/সোনাগাজী "},
  {"district_id": 5, "name": "Sonaimori/সোনাইমুড়ী "},
  {"district_id": 72, "name": "Sonali Bank Colony/সোনালী ব্যাংক কলোনী "},
  {"district_id": 43, "name": "Sonargaon/সোনারগাঁ "},
  {"district_id": 14, "name": "Sonatala/সোনাতলা "},
  {"district_id": 71, "name": "South Banashree/দক্ষিন বনশ্রী "},
  {"district_id": 72, "name": "South Bashabo/দক্ষিন বাসাবো "},
  {"district_id": 72, "name": "South Jatrabari/দক্ষিন যাত্রাবাড়ী "},
  {"district_id": 72, "name": "South Khilgaon/দক্ষিন খিলগাঁও "},
  {"district_id": 72, "name": "South Rajarbagh/দক্ষিন রাজারবাগ "},
  {"district_id": 39, "name": "South Sunamganj/দক্ষিন সুনামগঞ্জ "},
  {"district_id": 71, "name": "South badda/দক্ষিন বাড্ডা "},
  {"district_id": 72, "name": "SouthEast Jatrabari/দক্ষিন-পুর্ব যাত্রাবাড়ী "},
  {"district_id": 61, "name": "Sreebordi/শ্রীবরদী "},
  {"district_id": 37, "name": "Sreemangal/শ্রীমঙ্গল "},
  {"district_id": 48, "name": "Sreenagar/শ্রীনগর "},
  {"district_id": 26, "name": "Sreepur/শ্রীপুর "},
  {"district_id": 41, "name": "Sreepur/শ্রীপুর "},
  {"district_id": 5, "name": "Subarnachar/সুবর্ণচর "},
  {"district_id": 71, "name": "Subastu Nogorvally/সুবাস্তু নগরবালয় "},
  {"district_id": 13, "name": "Sujanagar/সুজানগর "},
  {"district_id": 39, "name": "Sunamganj Sadar/সুনামগঞ্জ সদর "},
  {"district_id": 57, "name": "Sundarganj/সুন্দরগঞ্জ "},
  {"district_id": 72, "name": "Surya Sen Hall/সূরিয়া সেন হল "},
  {"district_id": 72, "name": "Sutrapur/সূত্রাপুর "},
  {"district_id": 72, "name": "Swamibagh Lane/স্বামীবাগঃ লেন "},
  {"district_id": 72, "name": "Swamibagh New Township/স্বামীবাঘ নিউ টাউনশিপ "},
  {"district_id": 72, "name": "Swarighat east/পুর্ব সোয়ারীঘাট "},
  {"district_id": 56, "name": "Syedpur/সয়ৈদপুর "},
  {"district_id": 36, "name": "Sylhet Sadar/সিলেট সদর "},
  {"district_id": 72, "name": "T & T Colony/টি & টি কলোনী "},
  {"district_id": 39, "name": "Tahirpur/তাহিরপুর "},
  {"district_id": 21, "name": "Tala/তালা "},
  {"district_id": 72, "name": "Tallabag/তল্লাবাগ "},
  {"district_id": 35, "name": "Taltali/তলতলী "},
  {"district_id": 71, "name": "Taltola Khilgoan/তালতলা খিলগঞ্জ "},
  {"district_id": 44, "name": "Tangail Sadar/টাঙ্গাইল সদর "},
  {"district_id": 15, "name": "Tanore/তানোর"},
  {"district_id": 72, "name": "Tanuganj Lane/তানুগঞ্জ লেন "},
  {"district_id": 59, "name": "Taragonj/তারাগঞ্জ "},
  {"district_id": 45, "name": "Tarail/তাড়াইল "},
  {"district_id": 62, "name": "Tarakanda/তারাকান্দা "},
  {"district_id": 12, "name": "Tarash/তাড়াশ "},
  {"district_id": 34, "name": "Tazumuddin/তজুমুদ্দিন "},
  {"district_id": 71, "name": "Tejgaon/তেজগাঁও "},
  {
    "district_id": 71,
    "name": "Tejgaon - Gulshan Link Road/তেজগাঁও -গুলশান লিংক রোড "
  },
  {
    "district_id": 71,
    "name": "Tejgaon Industrial Area/তেজগাঁও লন্ডাট্রিয়াল এরিয়া "
  },
  {"district_id": 71, "name": "Tejkunipara/তেজকুনি পাড়া "},
  {"district_id": 71, "name": "Tek para/টেক পাড়া"},
  {"district_id": 9, "name": "Teknaf/টেকনাফ "},
  {"district_id": 71, "name": "Television Museum/টেলিভশন মুউজিয়াম "},
  {"district_id": 27, "name": "Terokhada/তেরখাদা "},
  {"district_id": 53, "name": "Tetulia/তেঁতুলিয়া "},
  {"district_id": 72, "name": "Thakurdas Lane/ঠাকুরদাস লেন "},
  {"district_id": 58, "name": "Thakurgaon Sadar/ঠাকুরগাঁও সদর "},
  {"district_id": 11, "name": "Thanchi/থানচি "},
  {"district_id": 71, "name": "Tibbet Factory/তিব্বত ফ্যাক্টরি "},
  {"district_id": 72, "name": "Tikatuli/টিকাটুলি "},
  {"district_id": 71, "name": "Tilpa Para/শিল্প পাড়া "},
  {"district_id": 72, "name": "Tipu Sultan Road/টিপু সুলতান রোড "},
  {"district_id": 1, "name": "Titas/তিতাস "},
  {"district_id": 71, "name": "Titas Road/তিতাস রোড "},
  {"district_id": 72, "name": "Titumir Hall/তিতুমীর হল "},
  {"district_id": 48, "name": "Tongibari/টঙ্গীবাড়ী "},
  {"district_id": 72, "name": "Topkhana Road/তোপখানা রোড "},
  {"district_id": 72, "name": "Toynbee Circular Road/তয়নবী সার্কুলার রোড "},
  {
    "district_id": 72,
    "name": "Traffic Police Barracks/ট্রাফিক পুলিশ ব্যারাকস "
  },
  {"district_id": 71, "name": "Trimohoni Bazar/ত্রিমোহনী বাজার "},
  {"district_id": 71, "name": "Trimohoni Bridge/ত্রিমোহনী ব্রিজ "},
  {"district_id": 62, "name": "Trishal/ত্রিশাল "},
  {"district_id": 71, "name": "Truckstand/ট্রাকস্ট্যান্ড "},
  {"district_id": 51, "name": "Tungipara/টুঙ্গিপাড়া "},
  {"district_id": 9, "name": "Ukhiya/উখিয়া "},
  {"district_id": 60, "name": "Ulipur/উলিপুর "},
  {"district_id": 12, "name": "Ullapara/উল্লাপাড়া "},
  {"district_id": 71, "name": "Ulon/উলং "},
  {"district_id": 72, "name": "Ultiganj Lane/উলটিগঞ্জ লেন "},
  {"district_id": 71, "name": "Uttar badda/উত্তর বাড্ডা "},
  {"district_id": 71, "name": "Uttara/উত্তরা "},
  {"district_id": 71, "name": "Uttara 1, 3, 5, 14/উতরা ১,৩,৫,১৪ "},
  {"district_id": 71, "name": "Uttara 7, 12, 13/উত্তরা ৭,১২,১৩"},
  {"district_id": 71, "name": "Uttara 9, 10, 11/উত্তরা ৯,১০,১১"},
  {"district_id": 71, "name": "Uttara Airport/উত্তরা এয়ারপোর্ট "},
  {"district_id": 71, "name": "Uttara Sector 1/উত্তরা সেক্টর ১"},
  {"district_id": 71, "name": "Uttara Sector 10/উত্তরা সেক্টর ১০"},
  {"district_id": 71, "name": "Uttara Sector 11/উত্তরা সেক্টর ১১"},
  {"district_id": 71, "name": "Uttara Sector 12/উতরা সেক্টর ১২"},
  {"district_id": 71, "name": "Uttara Sector 13/উতরা সেক্টর ১৩ "},
  {"district_id": 71, "name": "Uttara Sector 13"},
  {"district_id": 71, "name": "Uttara Sector 14"},
  {"district_id": 71, "name": "Uttara Sector 15"},
  {"district_id": 71, "name": "Uttara Sector 2"},
  {"district_id": 71, "name": "Uttara Sector 3"},
  {"district_id": 71, "name": "Uttara Sector 4"},
  {"district_id": 71, "name": "Uttara Sector 5"},
  {"district_id": 71, "name": "Uttara Sector 6"},
  {"district_id": 71, "name": "Uttara Sector 7"},
  {"district_id": 71, "name": "Uttara Sector 8"},
  {"district_id": 71, "name": "Uttara Sector 9"},
  {"district_id": 71, "name": "Uttargao"},
  {"district_id": 71, "name": "Uttarkhan"},
  {"district_id": 71, "name": "Vashantek"},
  {"district_id": 71, "name": "Vatara"},
  {"district_id": 71, "name": "Vatara mor"},
  {"district_id": 72, "name": "WHO Mission Road"},
  {"district_id": 72, "name": "Walter Road"},
  {"district_id": 72, "name": "Wapda Colony"},
  {"district_id": 72, "name": "Wari"},
  {"district_id": 72, "name": "Wari Street"},
  {"district_id": 33, "name": "Wazirpur"},
  {"district_id": 72, "name": "West Bashabo"},
  {"district_id": 72, "name": "West End Street"},
  {"district_id": 71, "name": "West Hazipara"},
  {"district_id": 72, "name": "West Jatrabari"},
  {"district_id": 72, "name": "West Juraine"},
  {"district_id": 72, "name": "West Malibag"},
  {"district_id": 71, "name": "West Nakhalpara"},
  {"district_id": 71, "name": "West Rampura"},
  {"district_id": 72, "name": "West fulbarai area"},
  {"district_id": 72, "name": "West old railway colony"},
  {"district_id": 71, "name": "Wireless More Bus Stop"},
  {"district_id": 72, "name": "Wise Ghat Road"},
  {"district_id": 72, "name": "Yoga Narayans Seal Street"},
  {"district_id": 72, "name": "Zahur Haque Hall"},
  {"district_id": 42, "name": "Zajira"},
  {"district_id": 36, "name": "Zakiganj"},
  {"district_id": 32, "name": "Zianagar"},
  {"district_id": 72, "name": "Ziaur Rahman Hall"},
  {"district_id": 72, "name": "central public library"},
  {"district_id": 75, "name": "Adabar"},
  {"district_id": 81, "name": "Bangsal/ বংশাল"},
  {"district_id": 81, "name": "Chowkbazar/ চকবাজার"},
  {"district_id": 81, "name": "Demra/ ডেমরা"},
  {"district_id": 81, "name": "Dhanmondi/ ধানমন্ডি"},
  {"district_id": 81, "name": "Gendaria/ গেন্ডারিয়া"},
  {"district_id": 81, "name": "Hazaribagh/ হাজারিবাগ"},
  {"district_id": 81, "name": "Jatrabari/ যাত্রাবাড়ি"},
  {"district_id": 81, "name": "Kalabagan/ কলাবাগান"},
  {"district_id": 81, "name": "Kamrangirchar/ কামরাঙ্গিরচর "},
  {"district_id": 81, "name": "Khilgaon/ খিলগাও"},
  {"district_id": 81, "name": "Kotwali/ কোতয়ালি"},
  {"district_id": 81, "name": "Lalbagh/ লালবাগ"},
  {"district_id": 81, "name": "Motijheel/ মতিঝিল"},
  {"district_id": 81, "name": "New Market/ নিউ-মার্কেট"},
  {"district_id": 81, "name": "Paltan/ পল্টন"},
  {"district_id": 81, "name": "Ramna/ রমনা"},
  {"district_id": 81, "name": "Sabujbagh/ সবুজবাগ"},
  {"district_id": 81, "name": "Shahbagh/ শাহবাগ"},
  {"district_id": 81, "name": "Shyampur/ শ্যামপুর"},
  {"district_id": 81, "name": "Sutrapur/ সুত্রাপুর"},
  {"district_id": 81, "name": "Wari/ ওয়ারি"},
  {"district_id": 81, "name": "Other/ অন্যানা"},
  {"district_id": 80, "name": "Adabor/ আদাবর"},
  {"district_id": 80, "name": "Banani/ বনানী "},
  {"district_id": 80, "name": "Bimanbandar/ বিমানবন্দর "},
  {"district_id": 80, "name": "Dhaka Cantonment/ ঢাকা ক্যান্টমেন্ট "},
  {"district_id": 80, "name": "Gulshan/ গুলশান "},
  {"district_id": 80, "name": "Hatirjheel/ হাতিরঝিল "},
  {"district_id": 80, "name": "Khilkhet/ খিলক্ষেত "},
  {"district_id": 80, "name": "Mirpur/ মিরপুর"},
  {"district_id": 80, "name": "Mohammadpur/ মোহাম্মদপুর"},
  {"district_id": 80, "name": "Pallabi/ পল্লবি"},
  {"district_id": 80, "name": "Rampura/ রামপুরা "},
  {"district_id": 80, "name": "Sher-e-Bangla Nagar/ শের-এ-বাংলা নগর "},
  {"district_id": 80, "name": "Tejgaon/ তেজগাও "},
  {"district_id": 80, "name": "Uttara/ উত্তরা "},
  {"district_id": 80, "name": "Uttarkhan/ উত্তরখান "},
  {"district_id": 80, "name": "Vatara/ ভাটারা "},
  {"district_id": 80, "name": "Other/ অন্যানা"},
];
