final List thanaListJson = [
  {"district_id": 72, "name": "AC Roy road"},
  {"district_id": 72, "name": "Abdul Hadi Lane"},
  {"district_id": 72, "name": "Abdul bani road"},
  {"district_id": 72, "name": "Abed Dali Road"},
  {"district_id": 20, "name": "Abhaynagar"},
  {"district_id": 72, "name": "Abhidas Lane"},
  {"district_id": 72, "name": "Abul Hasnat Road"},
  {"district_id": 71, "name": "Abul Hotel Bus Stop"},
  {"district_id": 72, "name": "Abul hasnat lane"},
  {"district_id": 72, "name": "Abul khairat Road"},
  {"district_id": 72, "name": "Abul khairat Road"},
  {"district_id": 71, "name": "Adabor"},
  {"district_id": 14, "name": "Adamdighi"},
  {"district_id": 71, "name": "Adarsha Bag"},
  {"district_id": 55, "name": "Aditmari"},
  {"district_id": 71, "name": "Aftab nagar"},
  {"district_id": 72, "name": "Aga sadek road"},
  {"district_id": 33, "name": "Agailjhara"},
  {"district_id": 72, "name": "Agamasi Lane"},
  {"district_id": 71, "name": "Agargaon"},
  {"district_id": 71, "name": "Ahmed Nagar"},
  {"district_id": 72, "name": "Ahmedbagh"},
  {"district_id": 72, "name": "Ahsan Ullah Road"},
  {"district_id": 38, "name": "Ajmiriganj"},
  {"district_id": 71, "name": "Ajompur"},
  {"district_id": 3, "name": "Akhaura"},
  {"district_id": 17, "name": "Akkelpur"},
  {"district_id": 72, "name": "Akshay Das Lane"},
  {"district_id": 72, "name": "Al Amin Road"},
  {"district_id": 24, "name": "Alamdanga"},
  {"district_id": 72, "name": "Alamganj Road"},
  {"district_id": 52, "name": "Alfadanga"},
  {"district_id": 72, "name": "Ali hossain Khan lane"},
  {"district_id": 11, "name": "Alikadam"},
  {"district_id": 72, "name": "Aminabad colony moghbaraz"},
  {"district_id": 72, "name": "Aminbagh"},
  {"district_id": 35, "name": "Amtali"},
  {"district_id": 71, "name": "Ananda Nagar"},
  {"district_id": 72, "name": "Anond mohan boshak Lane"},
  {"district_id": 8, "name": "Anwara"},
  {"district_id": 71, "name": "Apollo Hospital"},
  {"district_id": 43, "name": "Araihazar"},
  {"district_id": 72, "name": "Arambagh"},
  {"district_id": 71, "name": "Arjat Para"},
  {"district_id": 71, "name": "Armanitola"},
  {"district_id": 72, "name": "Armenium Street"},
  {"district_id": 71, "name": "Army Stadium"},
  {"district_id": 71, "name": "Asad Gate"},
  {"district_id": 71, "name": "Ashalota"},
  {"district_id": 72, "name": "Ashik lane"},
  {"district_id": 71, "name": "Ashkona"},
  {"district_id": 3, "name": "Ashuganj"},
  {"district_id": 21, "name": "Assasuni"},
  {"district_id": 13, "name": "Atghoria"},
  {"district_id": 64, "name": "Atpara"},
  {"district_id": 19, "name": "Atrai"},
  {"district_id": 53, "name": "Atwari"},
  {"district_id": 45, "name": "Austagram"},
  {"district_id": 72, "name": "Ayub Ali colony Rahim square"},
  {"district_id": 72, "name": "Azimpur"},
  {"district_id": 72, "name": "Azizullah Road"},
  {"district_id": 72, "name": "BDR Pilkhana"},
  {"district_id": 72, "name": "BK Roy Lane"},
  {"district_id": 33, "name": "Babuganj"},
  {"district_id": 19, "name": "Badalgachi"},
  {"district_id": 59, "name": "Badargonj"},
  {"district_id": 71, "name": "Badda"},
  {"district_id": 71, "name": "Badda Hossain Market"},
  {"district_id": 72, "name": "Badhika boshak Lane"},
  {"district_id": 72, "name": "Bagamganj Lane"},
  {"district_id": 16, "name": "Bagatipara"},
  {"district_id": 71, "name": "Bagbari"},
  {"district_id": 72, "name": "Bagdasa Lane"},
  {"district_id": 28, "name": "Bagerhat Sadar"},
  {"district_id": 15, "name": "Bagha"},
  {"district_id": 4, "name": "Baghaichari"},
  {"district_id": 20, "name": "Bagherpara"},
  {"district_id": 15, "name": "Bagmara"},
  {"district_id": 72, "name": "Bahadurpur Lane"},
  {"district_id": 38, "name": "Bahubal"},
  {"district_id": 72, "name": "Bailey Square Moghbazar"},
  {"district_id": 71, "name": "Baily Road"},
  {"district_id": 72, "name": "Baitul Mukarram Stadium"},
  {"district_id": 45, "name": "Bajitpur"},
  {"district_id": 33, "name": "Bakerganj"},
  {"district_id": 72, "name": "Bakshibagh"},
  {"district_id": 36, "name": "Balaganj"},
  {"district_id": 58, "name": "Baliadangi"},
  {"district_id": 49, "name": "Baliakandi"},
  {"district_id": 35, "name": "Bamna"},
  {"district_id": 71, "name": "Banani Bus Stand"},
  {"district_id": 71, "name": "Banani DOHS"},
  {"district_id": 71, "name": "Banani Graveyard"},
  {"district_id": 71, "name": "Banani Naval Head Quarter"},
  {"district_id": 71, "name": "Banani Road No. 1 - 11"},
  {"district_id": 71, "name": "Banani Road No. 12 - 19"},
  {"district_id": 71, "name": "Banani Road No. 20 - 28"},
  {"district_id": 33, "name": "Banaripara"},
  {"district_id": 72, "name": "Banasree"},
  {"district_id": 71, "name": "Banasree Block A"},
  {"district_id": 71, "name": "Banasree Block C"},
  {"district_id": 71, "name": "Banasree Block D"},
  {"district_id": 71, "name": "Banasree Block E"},
  {"district_id": 71, "name": "Banasree Block J"},
  {"district_id": 71, "name": "Banasree Block K"},
  {"district_id": 3, "name": "Bancharampur"},
  {"district_id": 43, "name": "Bandar"},
  {"district_id": 11, "name": "Bandarban Sadar"},
  {"district_id": 72, "name": "Bangabandhu Avenue & Rest House"},
  {"district_id": 72, "name": "Bangabhaban"},
  {"district_id": 72, "name": "Bangladesh Bank Colony"},
  {"district_id": 72, "name": "Bangladesh Railway Barracks"},
  {"district_id": 72, "name": "Bangshal"},
  {"district_id": 72, "name": "Bangshal Road"},
  {"district_id": 38, "name": "Baniachong"},
  {"district_id": 8, "name": "Banshkhali"},
  {"district_id": 16, "name": "Baraigram"},
  {"district_id": 35, "name": "Barguna Sadar"},
  {"district_id": 64, "name": "Barhatta"},
  {"district_id": 71, "name": "Baridhara"},
  {"district_id": 71, "name": "Baridhara DOHS"},
  {"district_id": 33, "name": "Barisal Sadar"},
  {"district_id": 4, "name": "Barkal"},
  {"district_id": 37, "name": "Barlekha"},
  {"district_id": 71, "name": "Barontek"},
  {"district_id": 1, "name": "Barura"},
  {"district_id": 72, "name": "Basabo"},
  {"district_id": 44, "name": "Basail"},
  {"district_id": 72, "name": "Bashabo Ohaba Colony"},
  {"district_id": 72, "name": "Bashir uddin road"},
  {"district_id": 71, "name": "Bashtola"},
  {"district_id": 71, "name": "Bashundhara"},
  {"district_id": 71, "name": "Bashundhara"},
  {"district_id": 71, "name": "Bashundhara Block A"},
  {"district_id": 71, "name": "Bashundhara Block B"},
  {"district_id": 71, "name": "Bashundhara Block C"},
  {"district_id": 71, "name": "Bashundhara Block D"},
  {"district_id": 71, "name": "Bashundhara Block F"},
  {"district_id": 71, "name": "Bashundhara Block H"},
  {"district_id": 71, "name": "Bashundhara Block I"},
  {"district_id": 71, "name": "Bashundhara Bus Stand"},
  {"district_id": 72, "name": "Bashundhara City"},
  {"district_id": 72, "name": "Basu Bazar Lane"},
  {"district_id": 71, "name": "Baunia"},
  {"district_id": 31, "name": "Bauphal"},
  {"district_id": 71, "name": "Bawlia Para"},
  {"district_id": 71, "name": "Bawneabad Area"},
  {"district_id": 36, "name": "Beanibazar"},
  {"district_id": 72, "name": "Begum Bazar"},
  {"district_id": 5, "name": "Begumganj"},
  {"district_id": 71, "name": "Begunbari"},
  {"district_id": 40, "name": "Belabo"},
  {"district_id": 4, "name": "Belaichari"},
  {"district_id": 12, "name": "Belkuchi"},
  {"district_id": 71, "name": "Bepari Bari"},
  {"district_id": 13, "name": "Bera"},
  {"district_id": 35, "name": "Betagi"},
  {"district_id": 72, "name": "Bhagwati Banerjee Road"},
  {"district_id": 45, "name": "Bhairab"},
  {"district_id": 62, "name": "Bhaluka"},
  {"district_id": 32, "name": "Bhandaria"},
  {"district_id": 52, "name": "Bhanga"},
  {"district_id": 13, "name": "Bhangura"},
  {"district_id": 42, "name": "Bhedarganj"},
  {"district_id": 25, "name": "Bheramara"},
  {"district_id": 72, "name": "Bhojhari Saha Street"},
  {"district_id": 34, "name": "Bhola Sadar"},
  {"district_id": 18, "name": "Bholahat"},
  {"district_id": 44, "name": "Bhuapur"},
  {"district_id": 60, "name": "Bhurungamari"},
  {"district_id": 71, "name": "Bhuyia Para"},
  {"district_id": 72, "name": "Bijoy Nagar"},
  {"district_id": 3, "name": "Bijoynagar"},
  {"district_id": 54, "name": "Birampur"},
  {"district_id": 54, "name": "Birganj"},
  {"district_id": 54, "name": "Birol"},
  {"district_id": 71, "name": "Bishteki"},
  {"district_id": 39, "name": "Bishwambarpur"},
  {"district_id": 36, "name": "Bishwanath"},
  {"district_id": 8, "name": "Boalkhali"},
  {"district_id": 52, "name": "Boalmari"},
  {"district_id": 54, "name": "Bochaganj"},
  {"district_id": 53, "name": "Boda"},
  {"district_id": 14, "name": "Bogra Sadar"},
  {"district_id": 63, "name": "Bokshiganj"},
  {"district_id": 71, "name": "Bonolota"},
  {"district_id": 34, "name": "Borhan Sddin"},
  {"district_id": 27, "name": "Botiaghata"},
  {"district_id": 71, "name": "Box Nagar"},
  {"district_id": 3, "name": "Brahmanbaria Sadar"},
  {"district_id": 1, "name": "Brahmanpara"},
  {"district_id": 1, "name": "Burichang"},
  {"district_id": 71, "name": "CDH Shampan"},
  {"district_id": 72, "name": "Central prison"},
  {"district_id": 71, "name": "Chairman bari"},
  {"district_id": 9, "name": "Chakaria"},
  {"district_id": 72, "name": "Chamelibagh"},
  {"district_id": 72, "name": "Champatli lane"},
  {"district_id": 8, "name": "Chandanaish"},
  {"district_id": 72, "name": "Chandi Charan Bose Street"},
  {"district_id": 1, "name": "Chandina"},
  {"district_id": 6, "name": "Chandpur Sadar"},
  {"district_id": 72, "name": "Chankharpul lane"},
  {"district_id": 18, "name": "Chapainawabganj Sadar"},
  {"district_id": 52, "name": "Charbhadrasan"},
  {"district_id": 34, "name": "Charfesson"},
  {"district_id": 15, "name": "Charghat"},
  {"district_id": 60, "name": "Charrajibpur"},
  {"district_id": 5, "name": "Chatkhil"},
  {"district_id": 13, "name": "Chatmohar"},
  {"district_id": 1, "name": "Chauddagram"},
  {"district_id": 12, "name": "Chauhali"},
  {"district_id": 72, "name": "Chawk Bazar"},
  {"district_id": 2, "name": "Chhagalnaiya"},
  {"district_id": 39, "name": "Chhatak"},
  {"district_id": 60, "name": "Chilmari"},
  {"district_id": 54, "name": "Chirirbandar"},
  {"district_id": 28, "name": "Chitalmari"},
  {"district_id": 71, "name": "Chittagong Road"},
  {"district_id": 72, "name": "Chota Katra"},
  {"district_id": 20, "name": "Chougachha"},
  {"district_id": 24, "name": "Chuadanga Sadar"},
  {"district_id": 38, "name": "Chunarughat"},
  {"district_id": 72, "name": "Circular Road"},
  {"district_id": 71, "name": "Coca Cola Bus Stop"},
  {"district_id": 1, "name": "Comilla Sadar"},
  {"district_id": 72, "name": "Committee ganj"},
  {"district_id": 5, "name": "Companiganj"},
  {"district_id": 36, "name": "Companiganj"},
  {"district_id": 71, "name": "Confidence Shopping Mall"},
  {"district_id": 72, "name": "Court House Street"},
  {"district_id": 9, "name": "Coxsbazar-Sadar"},
  {"district_id": 72, "name": "D.C Court"},
  {"district_id": 72, "name": "DC Roy Road"},
  {"district_id": 2, "name": "Daganbhuiyan"},
  {"district_id": 27, "name": "Dakop"},
  {"district_id": 71, "name": "Dakshinkhan"},
  {"district_id": 36, "name": "Dakshinsurma"},
  {"district_id": 42, "name": "Damudya"},
  {"district_id": 24, "name": "Damurhuda"},
  {"district_id": 71, "name": "Darus Salam"},
  {"district_id": 31, "name": "Dashmina"},
  {"district_id": 1, "name": "Daudkandi"},
  {"district_id": 25, "name": "Daulatpur"},
  {"district_id": 72, "name": "Dayaganj Jelepara"},
  {"district_id": 72, "name": "Dayaganj Road"},
  {"district_id": 21, "name": "Debhata"},
  {"district_id": 1, "name": "Debidwar"},
  {"district_id": 53, "name": "Debiganj"},
  {"district_id": 72, "name": "Deen Nath Sen Road"},
  {"district_id": 44, "name": "Delduar"},
  {"district_id": 72, "name": "Demra"},
  {"district_id": 39, "name": "Derai"},
  {"district_id": 72, "name": "Devidas Ghat Lane"},
  {"district_id": 63, "name": "Dewangonj"},
  {"district_id": 71, "name": "Dhaka - Cantonment"},
  {"district_id": 71, "name": "Dhaka - North City Corporation Market"},
  {"district_id": 72, "name": "Dhaka Cotton Mills"},
  {"district_id": 72, "name": "Dhaka University"},
  {"district_id": 72, "name": "Dhaka medical college"},
  {"district_id": 72, "name": "Dhalkanagar Lane"},
  {"district_id": 72, "name": "Dhalpur"},
  {"district_id": 19, "name": "Dhamoirhat"},
  {"district_id": 47, "name": "Dhamrai"},
  {"district_id": 71, "name": "Dhamrai"},
  {"district_id": 44, "name": "Dhanbari"},
  {"district_id": 72, "name": "Dhanmondi - Road No. 1 - 10"},
  {"district_id": 72, "name": "Dhanmondi 1"},
  {"district_id": 72, "name": "Dhanmondi 10"},
  {"district_id": 72, "name": "Dhanmondi 10A"},
  {"district_id": 72, "name": "Dhanmondi 11"},
  {"district_id": 72, "name": "Dhanmondi 11A"},
  {"district_id": 72, "name": "Dhanmondi 12"},
  {"district_id": 72, "name": "Dhanmondi 12A"},
  {"district_id": 72, "name": "Dhanmondi 13"},
  {"district_id": 72, "name": "Dhanmondi 13A"},
  {"district_id": 72, "name": "Dhanmondi 14"},
  {"district_id": 72, "name": "Dhanmondi 15"},
  {"district_id": 72, "name": "Dhanmondi 16"},
  {"district_id": 72, "name": "Dhanmondi 17"},
  {"district_id": 72, "name": "Dhanmondi 18"},
  {"district_id": 72, "name": "Dhanmondi 19"},
  {"district_id": 72, "name": "Dhanmondi 1A"},
  {"district_id": 72, "name": "Dhanmondi 2"},
  {"district_id": 72, "name": "Dhanmondi 20"},
  {"district_id": 72, "name": "Dhanmondi 21"},
  {"district_id": 72, "name": "Dhanmondi 22"},
  {"district_id": 72, "name": "Dhanmondi 23"},
  {"district_id": 72, "name": "Dhanmondi 24"},
  {"district_id": 72, "name": "Dhanmondi 25"},
  {"district_id": 72, "name": "Dhanmondi 26"},
  {"district_id": 72, "name": "Dhanmondi 27"},
  {"district_id": 72, "name": "Dhanmondi 28"},
  {"district_id": 72, "name": "Dhanmondi 29"},
  {"district_id": 72, "name": "Dhanmondi 2A"},
  {"district_id": 72, "name": "Dhanmondi 3"},
  {"district_id": 72, "name": "Dhanmondi 30"},
  {"district_id": 72, "name": "Dhanmondi 31"},
  {"district_id": 72, "name": "Dhanmondi 32"},
  {"district_id": 72, "name": "Dhanmondi 3A"},
  {"district_id": 72, "name": "Dhanmondi 4"},
  {"district_id": 72, "name": "Dhanmondi 4A"},
  {"district_id": 72, "name": "Dhanmondi 5"},
  {"district_id": 72, "name": "Dhanmondi 5A"},
  {"district_id": 72, "name": "Dhanmondi 6"},
  {"district_id": 72, "name": "Dhanmondi 6A"},
  {"district_id": 72, "name": "Dhanmondi 7"},
  {"district_id": 72, "name": "Dhanmondi 7A"},
  {"district_id": 72, "name": "Dhanmondi 8"},
  {"district_id": 72, "name": "Dhanmondi 8A"},
  {"district_id": 72, "name": "Dhanmondi 9"},
  {"district_id": 72, "name": "Dhanmondi 9A"},
  {"district_id": 72, "name": "Dhanmondi Road No. 11 - 16"},
  {"district_id": 72, "name": "Dhanmondi Road No. 1A - 13A"},
  {"district_id": 72, "name": "Dhanmondi Staff Quarter"},
  {"district_id": 39, "name": "Dharmapasha"},
  {"district_id": 62, "name": "Dhobaura"},
  {"district_id": 72, "name": "Dholaipar"},
  {"district_id": 14, "name": "Dhunot"},
  {"district_id": 71, "name": "Diabari"},
  {"district_id": 10, "name": "Dighinala"},
  {"district_id": 27, "name": "Digholia"},
  {"district_id": 72, "name": "Digu Babu Lane"},
  {"district_id": 72, "name": "Dilkusha"},
  {"district_id": 72, "name": "Dilkusha Commercial Area"},
  {"district_id": 56, "name": "Dimla"},
  {"district_id": 54, "name": "Dinajpur Sadar"},
  {"district_id": 71, "name": "Doctor Goli"},
  {"district_id": 47, "name": "Dohar"},
  {"district_id": 71, "name": "Dokkhingao"},
  {"district_id": 56, "name": "Domar"},
  {"district_id": 34, "name": "Doulatkhan"},
  {"district_id": 46, "name": "Doulatpur"},
  {"district_id": 39, "name": "Dowarabazar"},
  {"district_id": 72, "name": "Dr. M A Rashid Hall"},
  {"district_id": 31, "name": "Dumki"},
  {"district_id": 27, "name": "Dumuria"},
  {"district_id": 14, "name": "Dupchanchia"},
  {"district_id": 15, "name": "Durgapur"},
  {"district_id": 64, "name": "Durgapur"},
  {"district_id": 72, "name": "East Bashabo"},
  {"district_id": 71, "name": "East Hazipara"},
  {"district_id": 71, "name": "East Merul Badda"},
  {"district_id": 71, "name": "East Nakhalpara"},
  {"district_id": 71, "name": "East Nurerchala"},
  {"district_id": 72, "name": "East Raibazar"},
  {"district_id": 71, "name": "East Rampura"},
  {"district_id": 72, "name": "Eastern Housing"},
  {"district_id": 72, "name": "Elephant Road"},
  {"district_id": 72, "name": "Engineering University & Residential Area"},
  {"district_id": 72, "name": "English Road"},
  {"district_id": 72, "name": "Eskaton Garden Road"},
  {"district_id": 72, "name": "Fakirapul"},
  {"district_id": 72, "name": "Fakirapul Market Area"},
  {"district_id": 28, "name": "Fakirhat"},
  {"district_id": 72, "name": "Farashgang Lane"},
  {"district_id": 72, "name": "Faridabad Lane"},
  {"district_id": 6, "name": "Faridgonj"},
  {"district_id": 13, "name": "Faridpur"},
  {"district_id": 52, "name": "Faridpur Sadar"},
  {"district_id": 71, "name": "Farmgate"},
  {"district_id": 8, "name": "Fatikchhari"},
  {"district_id": 36, "name": "Fenchuganj"},
  {"district_id": 2, "name": "Feni Sadar"},
  {"district_id": 72, "name": "Folder Street"},
  {"district_id": 72, "name": "French Road"},
  {"district_id": 54, "name": "Fulbari"},
  {"district_id": 62, "name": "Fulbaria"},
  {"district_id": 72, "name": "Fulbaria Station East Area"},
  {"district_id": 2, "name": "Fulgazi"},
  {"district_id": 27, "name": "Fultola"},
  {"district_id": 14, "name": "Gabtali"},
  {"district_id": 71, "name": "Gabtoli Bus Terminal"},
  {"district_id": 62, "name": "Gafargaon"},
  {"district_id": 57, "name": "Gaibandha Sadar"},
  {"district_id": 48, "name": "Gajaria"},
  {"district_id": 31, "name": "Galachipa"},
  {"district_id": 59, "name": "Gangachara"},
  {"district_id": 22, "name": "Gangni"},
  {"district_id": 72, "name": "Ganguly Lane"},
  {"district_id": 41, "name": "Gazipur Sadar"},
  {"district_id": 72, "name": "Gendaria"},
  {"district_id": 72, "name": "Ghaji Osman Gani Road"},
  {"district_id": 44, "name": "Ghatail"},
  {"district_id": 54, "name": "Ghoraghat"},
  {"district_id": 46, "name": "Gior"},
  {"district_id": 49, "name": "Goalanda"},
  {"district_id": 57, "name": "Gobindaganj"},
  {"district_id": 15, "name": "Godagari"},
  {"district_id": 72, "name": "Golakpal Lane"},
  {"district_id": 72, "name": "Golam Mostafa Lane"},
  {"district_id": 36, "name": "Golapganj"},
  {"district_id": 71, "name": "Golartek"},
  {"district_id": 18, "name": "Gomostapur"},
  {"district_id": 51, "name": "Gopalganj Sadar"},
  {"district_id": 44, "name": "Gopalpur"},
  {"district_id": 72, "name": "Gopibagh"},
  {"district_id": 72, "name": "Gopinath Dutt Kabiraj Street"},
  {"district_id": 72, "name": "Goran"},
  {"district_id": 71, "name": "Goran Tampoo stand"},
  {"district_id": 42, "name": "Gosairhat"},
  {"district_id": 62, "name": "Gouripur"},
  {"district_id": 33, "name": "Gournadi"},
  {"district_id": 72, "name": "Govinda das lane"},
  {"district_id": 36, "name": "Gowainghat"},
  {"district_id": 72, "name": "Green Corner paribag"},
  {"district_id": 72, "name": "Green Road East"},
  {"district_id": 72, "name": "Green Road Staff Quarter"},
  {"district_id": 72, "name": "Green Road West"},
  {"district_id": 72, "name": "Green Square"},
  {"district_id": 72, "name": "Green corner green road"},
  {"district_id": 10, "name": "Guimara"},
  {"district_id": 72, "name": "Gulbagh"},
  {"district_id": 72, "name": "Gulistan"},
  {"district_id": 71, "name": "Gulshan 1"},
  {"district_id": 71, "name": "Gulshan 2"},
  {"district_id": 71, "name": "Gulshan Badda link Road"},
  {"district_id": 16, "name": "Gurudaspur"},
  {"district_id": 38, "name": "Habiganj Sadar"},
  {"district_id": 72, "name": "Hafiz Ullah Road"},
  {"district_id": 6, "name": "Haimchar"},
  {"district_id": 72, "name": "Haji Afsaruddin Road"},
  {"district_id": 72, "name": "Haji Mohammad Moshin Hall"},
  {"district_id": 6, "name": "Hajiganj"},
  {"district_id": 72, "name": "Hakim Habibur Rahman Road"},
  {"district_id": 54, "name": "Hakimpur"},
  {"district_id": 62, "name": "Haluaghat"},
  {"district_id": 72, "name": "Hari Parashanna Mitra Road"},
  {"district_id": 72, "name": "Hari Street"},
  {"district_id": 72, "name": "Haricharan Roy Road"},
  {"district_id": 29, "name": "Harinakundu"},
  {"district_id": 58, "name": "Haripur"},
  {"district_id": 46, "name": "Harirampur"},
  {"district_id": 72, "name": "Harish chand lane basu street"},
  {"district_id": 72, "name": "Hatembagh"},
  {"district_id": 8, "name": "Hathazari"},
  {"district_id": 5, "name": "Hatia"},
  {"district_id": 55, "name": "Hatibandha"},
  {"district_id": 71, "name": "Hatirjheel"},
  {"district_id": 72, "name": "Hatirpool Free school Street"},
  {"district_id": 72, "name": "Hatkhola Road"},
  {"district_id": 72, "name": "Hazaribagh"},
  {"district_id": 71, "name": "Hazi Camp"},
  {"district_id": 72, "name": "Hazi mainuddin Road"},
  {"district_id": 72, "name": "Hemendra das lane"},
  {"district_id": 72, "name": "High court Staff quarter"},
  {"district_id": 33, "name": "Hizla"},
  {"district_id": 1, "name": "Homna"},
  {"district_id": 45, "name": "Hossainpur"},
  {"district_id": 71, "name": "House Building"},
  {"district_id": 71, "name": "ICDDRB"},
  {"district_id": 71, "name": "Ibrahimpur"},
  {"district_id": 72, "name": "Imam Gang"},
  {"district_id": 72, "name": "Indrapuri"},
  {"district_id": 13, "name": "Ishurdi"},
  {"district_id": 63, "name": "Islampur"},
  {"district_id": 72, "name": "Islampur"},
  {"district_id": 62, "name": "Iswarganj"},
  {"district_id": 45, "name": "Itna"},
  {"district_id": 72, "name": "Jadab Narayandas lane"},
  {"district_id": 72, "name": "Jagannath Hall"},
  {"district_id": 39, "name": "Jagannathpur"},
  {"district_id": 71, "name": "Jahangir Gate"},
  {"district_id": 71, "name": "Jahurul Haque City"},
  {"district_id": 36, "name": "Jaintiapur"},
  {"district_id": 56, "name": "Jaldhaka"},
  {"district_id": 39, "name": "Jamalganj"},
  {"district_id": 63, "name": "Jamalpur Sadar"},
  {"district_id": 71, "name": "Jamuna Future Park"},
  {"district_id": 71, "name": "Jashimuddin Road"},
  {"district_id": 72, "name": "Jatrabari"},
  {"district_id": 72, "name": "Jayakali Mandir Road"},
  {"district_id": 20, "name": "Jessore Sadar"},
  {"district_id": 30, "name": "Jhalakathi Sadar"},
  {"district_id": 29, "name": "Jhenaidah Sadar"},
  {"district_id": 61, "name": "Jhenaigati"},
  {"district_id": 20, "name": "Jhikargacha"},
  {"district_id": 24, "name": "Jibannagar"},
  {"district_id": 71, "name": "Joar Shahara"},
  {"district_id": 72, "name": "Jorpool Lane"},
  {"district_id": 17, "name": "Joypurhat Sadar"},
  {"district_id": 72, "name": "Judge Court"},
  {"district_id": 72, "name": "Jumabali Lane"},
  {"district_id": 72, "name": "Jumma Beppari Lane"},
  {"district_id": 4, "name": "Juraichari"},
  {"district_id": 37, "name": "Juri"},
  {"district_id": 72, "name": "Justice Lalmohon Das Lane"},
  {"district_id": 72, "name": "K M Das Lane"},
  {"district_id": 72, "name": "K.M Azam Lane"},
  {"district_id": 72, "name": "K.Pk Ghosh Street"},
  {"district_id": 5, "name": "Kabirhat"},
  {"district_id": 6, "name": "Kachua"},
  {"district_id": 28, "name": "Kachua"},
  {"district_id": 72, "name": "Kadamtala"},
  {"district_id": 71, "name": "Kafrul"},
  {"district_id": 14, "name": "Kahaloo"},
  {"district_id": 54, "name": "Kaharol"},
  {"district_id": 72, "name": "Kakrail"},
  {"district_id": 72, "name": "Kalabagan"},
  {"district_id": 72, "name": "Kalabagan Free School Street"},
  {"district_id": 71, "name": "Kalachandpur"},
  {"district_id": 17, "name": "Kalai"},
  {"district_id": 31, "name": "Kalapara"},
  {"district_id": 21, "name": "Kalaroa"},
  {"district_id": 23, "name": "Kalia"},
  {"district_id": 41, "name": "Kaliakair"},
  {"district_id": 21, "name": "Kaliganj"},
  {"district_id": 29, "name": "Kaliganj"},
  {"district_id": 41, "name": "Kaliganj"},
  {"district_id": 55, "name": "Kaliganj"},
  {"district_id": 44, "name": "Kalihati"},
  {"district_id": 50, "name": "Kalkini"},
  {"district_id": 71, "name": "Kallyanpur"},
  {"district_id": 64, "name": "Kalmakanda"},
  {"district_id": 49, "name": "Kalukhali"},
  {"district_id": 72, "name": "Kamalapur"},
  {"district_id": 7, "name": "Kamalnagar"},
  {"district_id": 12, "name": "Kamarkhand"},
  {"district_id": 72, "name": "Kamlapur"},
  {"district_id": 37, "name": "Kamolganj"},
  {"district_id": 36, "name": "Kanaighat"},
  {"district_id": 41, "name": "Kapasia"},
  {"district_id": 4, "name": "Kaptai"},
  {"district_id": 45, "name": "Karimgonj"},
  {"district_id": 72, "name": "Karimullarbagh"},
  {"district_id": 8, "name": "Karnafuli"},
  {"district_id": 71, "name": "Karwan Bazar"},
  {"district_id": 72, "name": "Kasaituly"},
  {"district_id": 3, "name": "Kasba"},
  {"district_id": 51, "name": "Kashiani"},
  {"district_id": 30, "name": "Kathalia"},
  {"district_id": 72, "name": "Katherpul Lane"},
  {"district_id": 45, "name": "Katiadi"},
  {"district_id": 59, "name": "Kaunia"},
  {"district_id": 4, "name": "Kawkhali"},
  {"district_id": 32, "name": "Kawkhali"},
  {"district_id": 71, "name": "Kawranbazar"},
  {"district_id": 72, "name": "Kazi Zia uddin Lane"},
  {"district_id": 71, "name": "Kazipara"},
  {"district_id": 12, "name": "Kazipur"},
  {"district_id": 72, "name": "Kazirbagh"},
  {"district_id": 72, "name": "Kedar Nath"},
  {"district_id": 64, "name": "Kendua"},
  {"district_id": 47, "name": "Keraniganj"},
  {"district_id": 72, "name": "Keraniganj Sadar"},
  {"district_id": 72, "name": "Keshab Banarjee Road"},
  {"district_id": 20, "name": "Keshabpur"},
  {"district_id": 10, "name": "Khagrachhari Sadar"},
  {"district_id": 64, "name": "Khaliajuri"},
  {"district_id": 54, "name": "Khansama"},
  {"district_id": 17, "name": "Khetlal"},
  {"district_id": 71, "name": "Khilgaon"},
  {"district_id": 72, "name": "Khilgaon"},
  {"district_id": 72, "name": "Khilgaon Bagicha"},
  {"district_id": 72, "name": "Khilgaon Colony"},
  {"district_id": 71, "name": "Khilgoan Bus stop"},
  {"district_id": 71, "name": "Khilkhet"},
  {"district_id": 25, "name": "Khoksa"},
  {"district_id": 45, "name": "Kishoreganj Sadar"},
  {"district_id": 56, "name": "Kishorganj"},
  {"district_id": 71, "name": "Koloni Bazar"},
  {"district_id": 71, "name": "Koshaibari"},
  {"district_id": 51, "name": "Kotalipara"},
  {"district_id": 29, "name": "Kotchandpur"},
  {"district_id": 27, "name": "Koyra"},
  {"district_id": 37, "name": "Kulaura"},
  {"district_id": 45, "name": "Kuliarchar"},
  {"district_id": 25, "name": "Kumarkhali"},
  {"district_id": 71, "name": "Kunipara"},
  {"district_id": 60, "name": "Kurigram Sadar"},
  {"district_id": 71, "name": "Kuril"},
  {"district_id": 71, "name": "Kuril bus stop"},
  {"district_id": 71, "name": "Kurmitola"},
  {"district_id": 25, "name": "Kushtia Sadar"},
  {"district_id": 9, "name": "Kutubdia"},
  {"district_id": 72, "name": "Kuwait friendship hospital"},
  {"district_id": 38, "name": "Lakhai"},
  {"district_id": 1, "name": "Laksam"},
  {"district_id": 7, "name": "Lakshmipur Sadar"},
  {"district_id": 72, "name": "Lal Mohan Poddar Lane"},
  {"district_id": 72, "name": "Lalbagh"},
  {"district_id": 1, "name": "Lalmai"},
  {"district_id": 72, "name": "Lalmatia"},
  {"district_id": 34, "name": "Lalmohan"},
  {"district_id": 72, "name": "Lalmohan Shah Street"},
  {"district_id": 55, "name": "Lalmonirhat Sadar"},
  {"district_id": 16, "name": "Lalpur"},
  {"district_id": 11, "name": "Lama"},
  {"district_id": 4, "name": "Langadu"},
  {"district_id": 72, "name": "Large katra"},
  {"district_id": 10, "name": "Laxmichhari"},
  {"district_id": 8, "name": "Lohagara"},
  {"district_id": 23, "name": "Lohagara"},
  {"district_id": 48, "name": "Louhajanj"},
  {"district_id": 64, "name": "Madan"},
  {"district_id": 72, "name": "Madan Mohan Basak Road"},
  {"district_id": 72, "name": "Madanshah Lane"},
  {"district_id": 63, "name": "Madarganj"},
  {"district_id": 50, "name": "Madaripur Sadar"},
  {"district_id": 72, "name": "Madartek"},
  {"district_id": 38, "name": "Madhabpur"},
  {"district_id": 52, "name": "Madhukhali"},
  {"district_id": 44, "name": "Madhupur"},
  {"district_id": 26, "name": "Magura Sadar"},
  {"district_id": 72, "name": "Malakartola Lane"},
  {"district_id": 72, "name": "Malibag"},
  {"district_id": 71, "name": "Malibag bus stand"},
  {"district_id": 71, "name": "Malibag railgate"},
  {"district_id": 72, "name": "Malibagh Bazar Road"},
  {"district_id": 72, "name": "Malitola lane"},
  {"district_id": 19, "name": "Manda"},
  {"district_id": 72, "name": "Manik Nagar"},
  {"district_id": 72, "name": "Manik Nagar Miyazan Lane"},
  {"district_id": 10, "name": "Manikchari"},
  {"district_id": 71, "name": "Manikdi"},
  {"district_id": 46, "name": "Manikganj Sadar"},
  {"district_id": 72, "name": "Maniknagar"},
  {"district_id": 20, "name": "Manirampur"},
  {"district_id": 72, "name": "Maradia"},
  {"district_id": 71, "name": "Masranga Television"},
  {"district_id": 32, "name": "Mathbaria"},
  {"district_id": 71, "name": "Matikata"},
  {"district_id": 10, "name": "Matiranga"},
  {"district_id": 72, "name": "Matitola lane"},
  {"district_id": 6, "name": "Matlab North"},
  {"district_id": 6, "name": "Matlab South"},
  {"district_id": 72, "name": "Matuail"},
  {"district_id": 72, "name": "Mayakanon"},
  {"district_id": 1, "name": "Meghna"},
  {"district_id": 33, "name": "Mehendiganj"},
  {"district_id": 22, "name": "Meherpur Sadar"},
  {"district_id": 63, "name": "Melandah"},
  {"district_id": 71, "name": "Meradia"},
  {"district_id": 71, "name": "Meradia Graveyeard"},
  {"district_id": 71, "name": "Meradia kacha bazar"},
  {"district_id": 71, "name": "Merul"},
  {"district_id": 72, "name": "Methorpotty"},
  {"district_id": 72, "name": "Middle Bashabo"},
  {"district_id": 71, "name": "Middle Meradia"},
  {"district_id": 71, "name": "Middle badda"},
  {"district_id": 72, "name": "Mill Barracks"},
  {"district_id": 72, "name": "Mintu Road"},
  {"district_id": 72, "name": "Mir Hazaribagh"},
  {"district_id": 71, "name": "Mirbag"},
  {"district_id": 25, "name": "Mirpur"},
  {"district_id": 71, "name": "Mirpur 1"},
  {"district_id": 71, "name": "Mirpur 10"},
  {"district_id": 71, "name": "Mirpur 11 - 13"},
  {"district_id": 71, "name": "Mirpur 60 Feet"},
  {"district_id": 71, "name": "Mirpur Botanical Garden"},
  {"district_id": 71, "name": "Mirpur Cantonment"},
  {"district_id": 71, "name": "Mirpur Ceramic"},
  {"district_id": 71, "name": "Mirpur Colony"},
  {"district_id": 71, "name": "Mirpur DOHS"},
  {"district_id": 71, "name": "Mirpur Darus Salam"},
  {"district_id": 71, "name": "Mirpur Govt Housing Estate"},
  {"district_id": 71, "name": "Mirpur Kazipara"},
  {"district_id": 71, "name": "Mirpur Rupnagar"},
  {"district_id": 71, "name": "Mirpur Section 1"},
  {"district_id": 71, "name": "Mirpur Section 11"},
  {"district_id": 71, "name": "Mirpur Section 12"},
  {"district_id": 71, "name": "Mirpur Section 13"},
  {"district_id": 71, "name": "Mirpur Section 14"},
  {"district_id": 71, "name": "Mirpur Section 15"},
  {"district_id": 71, "name": "Mirpur Section 16"},
  {"district_id": 71, "name": "Mirpur Section 2"},
  {"district_id": 71, "name": "Mirpur Section 3"},
  {"district_id": 71, "name": "Mirpur Section 4"},
  {"district_id": 71, "name": "Mirpur Section 5"},
  {"district_id": 71, "name": "Mirpur Section 6"},
  {"district_id": 71, "name": "Mirpur Section 7"},
  {"district_id": 71, "name": "Mirpur Section 8"},
  {"district_id": 71, "name": "Mirpur Section 9"},
  {"district_id": 71, "name": "Mirpur Shewrapara"},
  {"district_id": 71, "name": "Mirpur Taltola"},
  {"district_id": 71, "name": "Mirpur Zoo"},
  {"district_id": 8, "name": "Mirsharai"},
  {"district_id": 31, "name": "Mirzaganj"},
  {"district_id": 44, "name": "Mirzapur"},
  {"district_id": 72, "name": "Mitali road"},
  {"district_id": 72, "name": "Mitfort Road"},
  {"district_id": 45, "name": "Mithamoin"},
  {"district_id": 59, "name": "Mithapukur"},
  {"district_id": 71, "name": "Modhubag"},
  {"district_id": 72, "name": "Mogbazar Circuit House Road"},
  {"district_id": 72, "name": "Moghbazar"},
  {"district_id": 72, "name": "Moghbazar TNT colony"},
  {"district_id": 19, "name": "Mohadevpur"},
  {"district_id": 71, "name": "Mohakhali"},
  {"district_id": 71, "name": "Mohakhali Bus Stand"},
  {"district_id": 71, "name": "Mohakhali DOHS"},
  {"district_id": 71, "name": "Mohakhali Inter District Bus Terminal"},
  {"district_id": 71, "name": "Mohakhali Kachabazar"},
  {"district_id": 71, "name": "Mohakhali TB Gate Jame Mosjid"},
  {"district_id": 71, "name": "Mohakhali koraill Basti"},
  {"district_id": 10, "name": "Mohalchari"},
  {"district_id": 71, "name": "Mohammadia Housing Limited"},
  {"district_id": 26, "name": "Mohammadpur"},
  {"district_id": 71, "name": "Mohammadpur Chandmiya Housing"},
  {"district_id": 71, "name": "Mohammadpur Mohammadia Housing Society"},
  {"district_id": 71, "name": "Mohammadpur Mohammadia Non Housing Area"},
  {"district_id": 71, "name": "Mohammadpur P C Culture Society"},
  {"district_id": 71, "name": "Mohammadpur Residential Area"},
  {"district_id": 9, "name": "Moheshkhali"},
  {"district_id": 29, "name": "Moheshpur"},
  {"district_id": 72, "name": "Mohini Mohandas Lane"},
  {"district_id": 64, "name": "Mohongonj"},
  {"district_id": 15, "name": "Mohonpur"},
  {"district_id": 72, "name": "Mokim Katara"},
  {"district_id": 28, "name": "Mollahat"},
  {"district_id": 72, "name": "Momenbagh"},
  {"district_id": 28, "name": "Mongla"},
  {"district_id": 71, "name": "Monipur"},
  {"district_id": 71, "name": "Monipuri Para"},
  {"district_id": 40, "name": "Monohardi"},
  {"district_id": 1, "name": "Monohargonj"},
  {"district_id": 34, "name": "Monpura"},
  {"district_id": 28, "name": "Morrelganj"},
  {"district_id": 72, "name": "Motijheel"},
  {"district_id": 72, "name": "Motijheel Colony"},
  {"district_id": 72, "name": "Motijheel Commercial Area"},
  {"district_id": 71, "name": "Mouchak"},
  {"district_id": 37, "name": "Moulvibazar Sadar"},
  {"district_id": 72, "name": "Mugda"},
  {"district_id": 72, "name": "Mugdapara"},
  {"district_id": 22, "name": "Mujibnagar"},
  {"district_id": 51, "name": "Muksudpur"},
  {"district_id": 62, "name": "Muktagacha"},
  {"district_id": 33, "name": "Muladi"},
  {"district_id": 72, "name": "Municipal Staff Quarter"},
  {"district_id": 72, "name": "Munir Hossain Lane"},
  {"district_id": 48, "name": "Munshiganj Sadar"},
  {"district_id": 1, "name": "Muradnagar"},
  {"district_id": 72, "name": "Muradpur"},
  {"district_id": 62, "name": "Mymensingh Sadar"},
  {"district_id": 72, "name": "Mymensingh lane"},
  {"district_id": 72, "name": "Nabalka Mia lane"},
  {"district_id": 38, "name": "Nabiganj"},
  {"district_id": 3, "name": "Nabinagar"},
  {"district_id": 71, "name": "Nabisco Bus Stand"},
  {"district_id": 18, "name": "Nachol"},
  {"district_id": 71, "name": "Nadda"},
  {"district_id": 52, "name": "Nagarkanda"},
  {"district_id": 44, "name": "Nagarpur"},
  {"district_id": 60, "name": "Nageshwari"},
  {"district_id": 11, "name": "Naikhongchhari"},
  {"district_id": 71, "name": "Nakhalpara"},
  {"district_id": 30, "name": "Nalchity"},
  {"district_id": 16, "name": "Naldanga"},
  {"district_id": 61, "name": "Nalitabari"},
  {"district_id": 71, "name": "Nama Para"},
  {"district_id": 62, "name": "Nandail"},
  {"district_id": 1, "name": "Nangalkot"},
  {"district_id": 4, "name": "Naniarchar"},
  {"district_id": 19, "name": "Naogaon Sadar"},
  {"district_id": 23, "name": "Narail Sadar"},
  {"district_id": 43, "name": "Narayanganj Sadar"},
  {"district_id": 42, "name": "Naria"},
  {"district_id": 72, "name": "Narinda Lane"},
  {"district_id": 72, "name": "Narinda Road"},
  {"district_id": 40, "name": "Narsingdi Sadar"},
  {"district_id": 71, "name": "Nasir er tek"},
  {"district_id": 3, "name": "Nasirnagar"},
  {"district_id": 72, "name": "National Museum Quarter"},
  {"district_id": 16, "name": "Natore Sadar"},
  {"district_id": 72, "name": "Naveen Chandra Gombasi Road"},
  {"district_id": 72, "name": "Nawab Deori"},
  {"district_id": 72, "name": "Nawab Katara"},
  {"district_id": 72, "name": "Nawab Street"},
  {"district_id": 47, "name": "Nawabganj"},
  {"district_id": 54, "name": "Nawabganj"},
  {"district_id": 72, "name": "Nawabganj"},
  {"district_id": 72, "name": "Nayapalton"},
  {"district_id": 72, "name": "Nazira Bazar Lane"},
  {"district_id": 32, "name": "Nazirpur"},
  {"district_id": 72, "name": "Nazrul Islam Hall"},
  {"district_id": 72, "name": "Neki Deori"},
  {"district_id": 32, "name": "Nesarabad"},
  {"district_id": 64, "name": "Netrokona Sadar"},
  {"district_id": 72, "name": "New Eskaton Road"},
  {"district_id": 72, "name": "New Jurain Alam Bagh"},
  {"district_id": 72, "name": "New market"},
  {"district_id": 19, "name": "Niamatpur"},
  {"district_id": 71, "name": "Niketon"},
  {"district_id": 71, "name": "Niketon Bazar gate"},
  {"district_id": 45, "name": "Nikli"},
  {"district_id": 71, "name": "Nikunja 1"},
  {"district_id": 71, "name": "Nikunja 2"},
  {"district_id": 72, "name": "Nilkhet Babupara"},
  {"district_id": 56, "name": "Nilphamari Sadar"},
  {"district_id": 5, "name": "Noakhali Sadar"},
  {"district_id": 61, "name": "Nokla"},
  {"district_id": 14, "name": "Nondigram"},
  {"district_id": 71, "name": "Nondipara"},
  {"district_id": 71, "name": "Nondipara Bazar"},
  {"district_id": 72, "name": "Noor box Lane"},
  {"district_id": 72, "name": "North Bashabo"},
  {"district_id": 72, "name": "North Circular Road"},
  {"district_id": 72, "name": "North Jatrabari"},
  {"district_id": 72, "name": "North Mugdapara Deputy Colony"},
  {"district_id": 72, "name": "North Rajarbagh"},
  {"district_id": 72, "name": "North Road"},
  {"district_id": 72, "name": "NorthEast Bashabo"},
  {"district_id": 72, "name": "NorthWest Jatrabari"},
  {"district_id": 71, "name": "Notunbag"},
  {"district_id": 71, "name": "Notunbazar Bus Stand"},
  {"district_id": 71, "name": "Noyatola"},
  {"district_id": 71, "name": "Nurer Chala"},
  {"district_id": 72, "name": "Old Railway Station"},
  {"district_id": 36, "name": "Osmaninagar"},
  {"district_id": 72, "name": "Outer Circular Road"},
  {"district_id": 72, "name": "PG Hospital"},
  {"district_id": 15, "name": "Paba"},
  {"district_id": 13, "name": "Pabna Sadar"},
  {"district_id": 72, "name": "Padma Nidhi Lane"},
  {"district_id": 72, "name": "Padmolochan Roy Lane"},
  {"district_id": 27, "name": "Paikgasa"},
  {"district_id": 71, "name": "Paikpara"},
  {"district_id": 45, "name": "Pakundia"},
  {"district_id": 72, "name": "Palamganj"},
  {"district_id": 40, "name": "Palash"},
  {"district_id": 57, "name": "Palashbari"},
  {"district_id": 72, "name": "Pallabi"},
  {"district_id": 72, "name": "Palton"},
  {"district_id": 53, "name": "Panchagarh Sadar"},
  {"district_id": 10, "name": "Panchari"},
  {"district_id": 17, "name": "Panchbibi"},
  {"district_id": 49, "name": "Pangsa"},
  {"district_id": 54, "name": "Parbatipur"},
  {"district_id": 72, "name": "Paribagh Shah Sahib Road"},
  {"district_id": 2, "name": "Parshuram"},
  {"district_id": 71, "name": "Paschim Rampura"},
  {"district_id": 55, "name": "Patgram"},
  {"district_id": 35, "name": "Pathorghata"},
  {"district_id": 8, "name": "Patiya"},
  {"district_id": 72, "name": "Patlakhan Lane"},
  {"district_id": 19, "name": "Patnitala"},
  {"district_id": 31, "name": "Patuakhali Sadar"},
  {"district_id": 72, "name": "Patuatuli Lane"},
  {"district_id": 9, "name": "Pekua"},
  {"district_id": 60, "name": "Phulbari"},
  {"district_id": 57, "name": "Phulchari"},
  {"district_id": 62, "name": "Phulpur"},
  {"district_id": 71, "name": "Pink City"},
  {"district_id": 71, "name": "Pirerbagh"},
  {"district_id": 59, "name": "Pirgacha"},
  {"district_id": 58, "name": "Pirganj"},
  {"district_id": 59, "name": "Pirgonj"},
  {"district_id": 32, "name": "Pirojpur Sadar"},
  {"district_id": 72, "name": "Poet Jasim Uddin Hall"},
  {"district_id": 72, "name": "Police Hospital"},
  {"district_id": 72, "name": "Police Line"},
  {"district_id": 71, "name": "Police Plaza"},
  {"district_id": 19, "name": "Porsha"},
  {"district_id": 72, "name": "Postagola"},
  {"district_id": 72, "name": "Postal Colony"},
  {"district_id": 71, "name": "Prembagan"},
  {"district_id": 72, "name": "Puran Mogul"},
  {"district_id": 72, "name": "Purana Paltan GPO"},
  {"district_id": 72, "name": "Purana Paltan Line"},
  {"district_id": 64, "name": "Purbadhala"},
  {"district_id": 15, "name": "Puthia"},
  {"district_id": 72, "name": "R K Mission Road"},
  {"district_id": 72, "name": "Rai Ishrat Chandta"},
  {"district_id": 12, "name": "Raigonj"},
  {"district_id": 72, "name": "Railway Hospital area"},
  {"district_id": 7, "name": "Raipur"},
  {"district_id": 40, "name": "Raipura"},
  {"district_id": 72, "name": "Rajabagh Police Line"},
  {"district_id": 72, "name": "Rajani Bose Lane"},
  {"district_id": 30, "name": "Rajapur"},
  {"district_id": 71, "name": "Rajarbag Police Line"},
  {"district_id": 60, "name": "Rajarhat"},
  {"district_id": 4, "name": "Rajasthali"},
  {"district_id": 49, "name": "Rajbari Sadar"},
  {"district_id": 37, "name": "Rajnagar"},
  {"district_id": 72, "name": "Rajni Chowdhury Road"},
  {"district_id": 50, "name": "Rajoir"},
  {"district_id": 72, "name": "Rakhal chandra bashak lane"},
  {"district_id": 7, "name": "Ramganj"},
  {"district_id": 10, "name": "Ramgarh"},
  {"district_id": 7, "name": "Ramgati"},
  {"district_id": 72, "name": "Ramna"},
  {"district_id": 28, "name": "Rampal"},
  {"district_id": 72, "name": "Rampura"},
  {"district_id": 71, "name": "Rampura Bazar"},
  {"district_id": 71, "name": "Rampura Bus Stand"},
  {"district_id": 9, "name": "Ramu"},
  {"district_id": 31, "name": "Rangabali"},
  {"district_id": 4, "name": "Rangamati Sadar"},
  {"district_id": 59, "name": "Rangpur Sadar"},
  {"district_id": 8, "name": "Rangunia"},
  {"district_id": 19, "name": "Raninagar"},
  {"district_id": 58, "name": "Ranisankail"},
  {"district_id": 8, "name": "Raozan"},
  {"district_id": 71, "name": "Rasulbagh"},
  {"district_id": 72, "name": "Rishikosh Das Road"},
  {"district_id": 72, "name": "Rokaya Hall"},
  {"district_id": 11, "name": "Rowangchhari"},
  {"district_id": 60, "name": "Rowmari"},
  {"district_id": 72, "name": "Roy Bahadur Road"},
  {"district_id": 72, "name": "Rubber Bose Street"},
  {"district_id": 72, "name": "Rui Hatra"},
  {"district_id": 11, "name": "Ruma"},
  {"district_id": 72, "name": "Rupa das lal lane"},
  {"district_id": 72, "name": "Rupchan Lane"},
  {"district_id": 43, "name": "Rupganj"},
  {"district_id": 27, "name": "Rupsha"},
  {"district_id": 72, "name": "Sabujbagh"},
  {"district_id": 52, "name": "Sadarpur"},
  {"district_id": 1, "name": "Sadarsouth"},
  {"district_id": 57, "name": "Sadullapur"},
  {"district_id": 57, "name": "Saghata"},
  {"district_id": 72, "name": "Saidabad"},
  {"district_id": 44, "name": "Sakhipur"},
  {"district_id": 72, "name": "Salimullah Hall"},
  {"district_id": 52, "name": "Saltha"},
  {"district_id": 72, "name": "Samaswada lane"},
  {"district_id": 8, "name": "Sandwip"},
  {"district_id": 13, "name": "Santhia"},
  {"district_id": 19, "name": "Sapahar"},
  {"district_id": 3, "name": "Sarail"},
  {"district_id": 28, "name": "Sarankhola"},
  {"district_id": 63, "name": "Sarishabari"},
  {"district_id": 72, "name": "Sarulia"},
  {"district_id": 72, "name": "Satish Sarkar Road"},
  {"district_id": 8, "name": "Satkania"},
  {"district_id": 21, "name": "Satkhira Sadar"},
  {"district_id": 72, "name": "Satmasjid Road"},
  {"district_id": 71, "name": "Satrasta"},
  {"district_id": 46, "name": "Saturia"},
  {"district_id": 47, "name": "Savar"},
  {"district_id": 72, "name": "Sayed hasan Ali Lane"},
  {"district_id": 72, "name": "Secretariat Road"},
  {"district_id": 72, "name": "Segun Bagicha"},
  {"district_id": 5, "name": "Senbug"},
  {"district_id": 72, "name": "Shah Shaheb Lane"},
  {"district_id": 72, "name": "Shahbagh"},
  {"district_id": 72, "name": "Shaheed Memorial Hall"},
  {"district_id": 72, "name": "Shahidbagh"},
  {"district_id": 72, "name": "Shahidullah Hall"},
  {"district_id": 71, "name": "Shahinbag"},
  {"district_id": 12, "name": "Shahjadpur"},
  {"district_id": 71, "name": "Shahjahadpur Bus Stand"},
  {"district_id": 72, "name": "Shahjahanpur"},
  {"district_id": 72, "name": "Shahjahanpur Railway Colony"},
  {"district_id": 71, "name": "Shahjahdpur"},
  {"district_id": 6, "name": "Shahrasti"},
  {"district_id": 29, "name": "Shailkupa"},
  {"district_id": 14, "name": "Shajahanpur"},
  {"district_id": 72, "name": "Shakhari Bazar Road"},
  {"district_id": 72, "name": "Shakhari Nagar Lane"},
  {"district_id": 26, "name": "Shalikha"},
  {"district_id": 39, "name": "Shalla"},
  {"district_id": 72, "name": "Shamsun Nahar Hall"},
  {"district_id": 72, "name": "Shantibagh"},
  {"district_id": 72, "name": "Shantinagar"},
  {"district_id": 72, "name": "Shantinagar Market Area"},
  {"district_id": 71, "name": "Shantiniketon"},
  {"district_id": 71, "name": "Shantipur"},
  {"district_id": 72, "name": "Sharat chandra chakraborty lane"},
  {"district_id": 72, "name": "Sharatgupta Road"},
  {"district_id": 14, "name": "Shariakandi"},
  {"district_id": 42, "name": "Shariatpur Sadar"},
  {"district_id": 71, "name": "Sharnalata"},
  {"district_id": 20, "name": "Sharsha"},
  {"district_id": 72, "name": "Shashibhushan Chaterjee Lane"},
  {"district_id": 72, "name": "Sheikh Majibur Rahman Hall"},
  {"district_id": 71, "name": "Shena Maloncha"},
  {"district_id": 71, "name": "Shenpara Parbata"},
  {"district_id": 72, "name": "Sher e Bangla Road"},
  {"district_id": 71, "name": "Sher-e-Bangla Nagar"},
  {"district_id": 72, "name": "Sherabangla Hall"},
  {"district_id": 14, "name": "Sherpur"},
  {"district_id": 61, "name": "Sherpur Sadar"},
  {"district_id": 71, "name": "Shewrapara"},
  {"district_id": 46, "name": "Shibaloy"},
  {"district_id": 50, "name": "Shibchar"},
  {"district_id": 14, "name": "Shibganj"},
  {"district_id": 18, "name": "Shibganj"},
  {"district_id": 40, "name": "Shibpur"},
  {"district_id": 71, "name": "Shiddheshwari"},
  {"district_id": 71, "name": "Shipahibag"},
  {"district_id": 71, "name": "Shonirakhra"},
  {"district_id": 72, "name": "Shukrabad"},
  {"district_id": 72, "name": "Shurwardi Hall"},
  {"district_id": 21, "name": "Shyamnagar"},
  {"district_id": 71, "name": "Shyamoli"},
  {"district_id": 72, "name": "Siddheshwari Road"},
  {"district_id": 72, "name": "Siddique bazar"},
  {"district_id": 72, "name": "Siddique lane"},
  {"district_id": 72, "name": "Sikkatuli lane"},
  {"district_id": 72, "name": "Simson Road"},
  {"district_id": 46, "name": "Singiar"},
  {"district_id": 16, "name": "Singra"},
  {"district_id": 71, "name": "Sipahi bag tampoo stand"},
  {"district_id": 72, "name": "Sir AF Rahman hall"},
  {"district_id": 48, "name": "Sirajdikhan"},
  {"district_id": 12, "name": "Sirajganj Sadar"},
  {"district_id": 8, "name": "Sitakunda"},
  {"district_id": 72, "name": "Sobhanbagh"},
  {"district_id": 71, "name": "Solmaid"},
  {"district_id": 71, "name": "Sona katra"},
  {"district_id": 2, "name": "Sonagazi"},
  {"district_id": 5, "name": "Sonaimori"},
  {"district_id": 72, "name": "Sonali Bank Colony"},
  {"district_id": 43, "name": "Sonargaon"},
  {"district_id": 14, "name": "Sonatala"},
  {"district_id": 71, "name": "South Banashree"},
  {"district_id": 72, "name": "South Bashabo"},
  {"district_id": 72, "name": "South Jatrabari"},
  {"district_id": 72, "name": "South Khilgaon"},
  {"district_id": 72, "name": "South Rajarbagh"},
  {"district_id": 39, "name": "South Sunamganj"},
  {"district_id": 71, "name": "South badda"},
  {"district_id": 72, "name": "SouthEast Jatrabari"},
  {"district_id": 61, "name": "Sreebordi"},
  {"district_id": 37, "name": "Sreemangal"},
  {"district_id": 48, "name": "Sreenagar"},
  {"district_id": 26, "name": "Sreepur"},
  {"district_id": 41, "name": "Sreepur"},
  {"district_id": 5, "name": "Subarnachar"},
  {"district_id": 71, "name": "Subastu Nogorvally"},
  {"district_id": 13, "name": "Sujanagar"},
  {"district_id": 39, "name": "Sunamganj Sadar"},
  {"district_id": 57, "name": "Sundarganj"},
  {"district_id": 72, "name": "Surya Sen Hall"},
  {"district_id": 72, "name": "Sutrapur"},
  {"district_id": 72, "name": "Swamibagh Lane"},
  {"district_id": 72, "name": "Swamibagh New Township"},
  {"district_id": 72, "name": "Swarighat east"},
  {"district_id": 56, "name": "Syedpur"},
  {"district_id": 36, "name": "Sylhet Sadar"},
  {"district_id": 72, "name": "T & T Colony"},
  {"district_id": 39, "name": "Tahirpur"},
  {"district_id": 21, "name": "Tala"},
  {"district_id": 72, "name": "Tallabag"},
  {"district_id": 35, "name": "Taltali"},
  {"district_id": 71, "name": "Taltola Khilgoan"},
  {"district_id": 44, "name": "Tangail Sadar"},
  {"district_id": 15, "name": "Tanore"},
  {"district_id": 72, "name": "Tanuganj Lane"},
  {"district_id": 59, "name": "Taragonj"},
  {"district_id": 45, "name": "Tarail"},
  {"district_id": 62, "name": "Tarakanda"},
  {"district_id": 12, "name": "Tarash"},
  {"district_id": 34, "name": "Tazumuddin"},
  {"district_id": 71, "name": "Tejgaon"},
  {"district_id": 71, "name": "Tejgaon - Gulshan Link Road"},
  {"district_id": 71, "name": "Tejgaon Industrial Area"},
  {"district_id": 71, "name": "Tejkunipara"},
  {"district_id": 71, "name": "Tek para"},
  {"district_id": 9, "name": "Teknaf"},
  {"district_id": 71, "name": "Television Museum"},
  {"district_id": 27, "name": "Terokhada"},
  {"district_id": 53, "name": "Tetulia"},
  {"district_id": 72, "name": "Thakurdas Lane"},
  {"district_id": 58, "name": "Thakurgaon Sadar"},
  {"district_id": 11, "name": "Thanchi"},
  {"district_id": 71, "name": "Tibbet Factory"},
  {"district_id": 72, "name": "Tikatuli"},
  {"district_id": 71, "name": "Tilpa Para"},
  {"district_id": 72, "name": "Tipu Sultan Road"},
  {"district_id": 1, "name": "Titas"},
  {"district_id": 71, "name": "Titas Road"},
  {"district_id": 72, "name": "Titumir Hall"},
  {"district_id": 48, "name": "Tongibari"},
  {"district_id": 72, "name": "Topkhana Road"},
  {"district_id": 72, "name": "Toynbee Circular Road"},
  {"district_id": 72, "name": "Traffic Police Barracks"},
  {"district_id": 71, "name": "Trimohoni Bazar"},
  {"district_id": 71, "name": "Trimohoni Bridge"},
  {"district_id": 62, "name": "Trishal"},
  {"district_id": 71, "name": "Truckstand"},
  {"district_id": 51, "name": "Tungipara"},
  {"district_id": 9, "name": "Ukhiya"},
  {"district_id": 60, "name": "Ulipur"},
  {"district_id": 12, "name": "Ullapara"},
  {"district_id": 71, "name": "Ulon"},
  {"district_id": 72, "name": "Ultiganj Lane"},
  {"district_id": 71, "name": "Uttar badda"},
  {"district_id": 71, "name": "Uttara"},
  {"district_id": 71, "name": "Uttara 1, 3, 5, 14"},
  {"district_id": 71, "name": "Uttara 7, 12, 13"},
  {"district_id": 71, "name": "Uttara 9, 10, 11"},
  {"district_id": 71, "name": "Uttara Airport"},
  {"district_id": 71, "name": "Uttara Sector 1"},
  {"district_id": 71, "name": "Uttara Sector 10"},
  {"district_id": 71, "name": "Uttara Sector 11"},
  {"district_id": 71, "name": "Uttara Sector 12"},
  {"district_id": 71, "name": "Uttara Sector 13"},
  {"district_id": 71, "name": "Uttara Sector 14"},
  {"district_id": 71, "name": "Uttara Sector 15"},
  {"district_id": 71, "name": "Uttara Sector 2"},
  {"district_id": 71, "name": "Uttara Sector 3"},
  {"district_id": 71, "name": "Uttara Sector 4"},
  {"district_id": 71, "name": "Uttara Sector 5"},
  {"district_id": 71, "name": "Uttara Sector 6"},
  {"district_id": 71, "name": "Uttara Sector 7"},
  {"district_id": 71, "name": "Uttara Sector 8"},
  {"district_id": 71, "name": "Uttara Sector 9"},
  {"district_id": 71, "name": "Uttargao"},
  {"district_id": 71, "name": "Uttarkhan"},
  {"district_id": 71, "name": "Vashantek"},
  {"district_id": 71, "name": "Vatara"},
  {"district_id": 71, "name": "Vatara mor"},
  {"district_id": 72, "name": "WHO Mission Road"},
  {"district_id": 72, "name": "Walter Road"},
  {"district_id": 72, "name": "Wapda Colony"},
  {"district_id": 72, "name": "Wari"},
  {"district_id": 72, "name": "Wari Street"},
  {"district_id": 33, "name": "Wazirpur"},
  {"district_id": 72, "name": "West Bashabo"},
  {"district_id": 72, "name": "West End Street"},
  {"district_id": 71, "name": "West Hazipara"},
  {"district_id": 72, "name": "West Jatrabari"},
  {"district_id": 72, "name": "West Juraine"},
  {"district_id": 72, "name": "West Malibag"},
  {"district_id": 71, "name": "West Nakhalpara"},
  {"district_id": 71, "name": "West Rampura"},
  {"district_id": 72, "name": "West fulbarai area"},
  {"district_id": 72, "name": "West old railway colony"},
  {"district_id": 71, "name": "Wireless More Bus Stop"},
  {"district_id": 72, "name": "Wise Ghat Road"},
  {"district_id": 72, "name": "Yoga Narayans Seal Street"},
  {"district_id": 72, "name": "Zahur Haque Hall"},
  {"district_id": 42, "name": "Zajira"},
  {"district_id": 36, "name": "Zakiganj"},
  {"district_id": 32, "name": "Zianagar"},
  {"district_id": 72, "name": "Ziaur Rahman Hall"},
  {"district_id": 72, "name": "central public library"},

  {"district_id": 75, "name": "Adabar"},

];
