final List occuptoinlist = [
  "Doctor",
  "Intern Doctor",
  "MATS Student",
  "Medical Student",
  "Nurse",
  "Nursing Student",
  "Pharmaceutical Professional",
  "SACMO",
  "Others"
];

final List thanatlist = [
  "Bagerhat",
  "Bandarban",
  "Barguna",
  "Barisal",
  "Bhola",
  "Bogra",
  "Brahmanbaria",
  "Chandpur",
  "Chuadanga"
  "Comilla",
  "Cox's Bazar",
  "Dhaka",
  "Faridpur",
  "Feni",
  "Gaibandha",
  "Gazipur",
  "Gopalganj",
  "Habiganj"
  "Jaipurhat"
"Jamalpur",
"Jessore",
"Jhalakati",
"Jhenaidah",
"Khagrachari",
"Khulna",
"Kishoreganj",
"Kurigram",
"Kushtia",
"Lakshmipur",
"Lalmonirhat",
"Madaripur",
"Magura",
"Manikganj",
"Meherpur",
"Moulvibazar",
"Munshiganj",
"Mymensingh",
"Naogaon",
"Narail",
"Narayanganj",
"Narsingdi",
"Natore",
"Nawabganj",
"Netrakona",
"Nilphamari",
"Noakhali",
"Pabna",
"Panchagarh",
"Parbattya Chattagram",
"Patuakhali",
"Pirojpur",
"Rajbari",
"Rajshahi",
"Rangpur",
"Satkhira",
"Shariatpur",
"Sherpur",
"Sirajganj",
"Sunamganj",
"Sylhet",
"Tangail",
"Thakurgaon",
];


final List districtlist = [
  "Bagerhat",
  "Bandarban",
  "Barguna",
  "Barisal",
  "Bhola",
  "Bogra",
  "Brahmanbaria",
  "Chandpur",
  "Chuadanga"
  "Comilla",
  "Cox's Bazar",
  "Dhaka",
  "Faridpur",
  "Feni",
  "Gaibandha",
  "Gazipur",
  "Gopalganj",
  "Habiganj"
  "Jaipurhat"
"Jamalpur",
"Jessore",
"Jhalakati",
"Jhenaidah",
"Khagrachari",
"Khulna",
"Kishoreganj",
"Kurigram",
"Kushtia",
"Lakshmipur",
"Lalmonirhat",
"Madaripur",
"Magura",
"Manikganj",
"Meherpur",
"Moulvibazar",
"Munshiganj",
"Mymensingh",
"Naogaon",
"Narail",
"Narayanganj",
"Narsingdi",
"Natore",
"Nawabganj",
"Netrakona",
"Nilphamari",
"Noakhali",
"Pabna",
"Panchagarh",
"Parbattya Chattagram",
"Patuakhali",
"Pirojpur",
"Rajbari",
"Rajshahi",
"Rangpur",
"Satkhira",
"Shariatpur",
"Sherpur",
"Sirajganj",
"Sunamganj",
"Sylhet",
"Tangail",
"Thakurgaon",
];



final List specalizationlist = [
  "Anesthesia & ICU Specialists",
  "Cancer Surgeons",
  "Cordio-Vascular Surgeons",
  "Cardiologists",
  "Colorectal Surgeons",
  "Critical Care Medicine Specialits",
  "Dentists",
  "Dermatologists",
  "Diabetologists"
  "ENT Specialists",
"Endocrinologists",
"Gastroenterologists",
"General & Laparosecopic Surgeons",
"General Physicians",
"Gynecologiss & Obstetricians",
"Hemaologists",
"Hepatobiliary Surgeons",
"Hepatologists",
"Infertility Specialists",
"Internal Medicine Specialists",
"Nephrologiss",
"Neuologists",
"Oncologists",
"Ophthalmologists",
"Orofacial & Maxillary Surgeons",
"Orthopaedic Surgeons",
"Pediatric Surgeons",
"Pediatricians",
"Physical Medicine Specialists",
"Plastic Surgeons",
"Psychiatrists",
"Respiratory Medicine Specialists",
"Rheumatology Specialists",
"Theoracic Surgeons",
"Urologist",
"Others",

];
